### ISSUE TITLE
DKIM documentation out of date

### ISSUE THREAD

**Issue by clarfon** [OpenSMTPD/OpenSMTPD#1011]
Right now, the man page still mentions dkimproxy without mentioning `opensmtpd-filter-dkimsign` and `opensmtpd-filter-rspamd`, which honestly should be used instead.

**Comment by ngortheone** [comment]
@clarfon, thanks for pointing out. 
`dkimproxy` is indeed an abandonware at this point, we absolutely should update the docs in favor of `opensmtpd-filter-dkimsign` and `opensmtpd-filter-rspamd`.
I'll see what I can do to improve documentation.

**Comment by poolpOrg** [comment]
This is a delicate subject, we need to find the _proper_ way to document that:

Before 6.6.0p1 there were only two options, `dkimproxy` which was fairly easy to setup, `spampd`+`whatever-dkim-signing-tool` which required more work, so most people wanted `dkimproxy` and we could just document that as this was THE way to do it.

Now, with filters, multiple options are available BUT we don't want the OpenSMTPD project to start endorsing specific filters because they are not official filters. If we add a specific filter to the documentation, it makes it somewhat endorsed by the project but maybe only one developer, the author, has actually read the code :-/

Does `opensmtpd-filter-dkimsign` work outside of OpenBSD ? 
And as for `opensmtpd-filter-rspamd` it only works for two architectures supported by OpenBSD :-/

**Comment by clarfon** [comment]
Honestly, I feel that DKIM is basically required for any email server, so, if there isn't an officially endorsed method for making it work, it may be worth either adopting the DKIM filter as part of the project or including it as an option without the need to filter.

Spam-filtering is a lot more subjective and it's understandable that rspamd integration wouldn't be incorporated into the project, but at least DKIM seems reasonable enough that there should be a recommended way to do it.

When looking through old issues I noticed that the ones requesting DKIM support were closed once the new filters were implemented, so, I had assumed that those were the new recommended ways of doing things.

**Comment by poolpOrg** [comment]
> Honestly, I feel that DKIM is basically required for any email server, so, if there isn't an officially endorsed method for making it work, it may be worth either adopting the DKIM filter as part of the project or including it as an option without the need to filter.
> 

Not endorsing doesn't mean not supporting, since filters are just one command away from install I don't think we need to endorse any as long as people can easily install them. We just need to find the proper way to document their integration.

> Spam-filtering is a lot more subjective and it's understandable that rspamd integration wouldn't be incorporated into the project, but at least DKIM seems reasonable enough that there should be a recommended way to do it.
> 

Yeah well that didn't work because three people already disagreed on wether DKIM should be a specific filter or be part of a more advanced DMARC filter. I'm not even part of the discussion given that I think a general purpose engine like Rspamd can cover these use-cases :-)

Even though DKIM is a mandatory component, its integration is more subjectif than you think, and if I'm committing an example tomorrow for my own filter, I'm pretty sure another author is going to think that this is a bit unfair to their work.

> When looking through old issues I noticed that the ones requesting DKIM support were closed once the new filters were implemented, so, I had assumed that those were the new recommended ways of doing things.
>

And they are but this doesn't mean OpenSMTPD will endorse all filters that cover common use-cases, my idea was to have a central place for filters (https://github.com/OpenSMTPD/addons) so that we would document that and not endorse a specific one.

**Comment by clarfon** [comment]
That is a fair point and things do seem to be a lot more subjective like you've mentioned.

Previously I had been trying to use postfix as a server and switching to opensmtpd vastly simplified the configuration due to the lack of a need for key functionality to be implemented through filters. It makes sense to at least point people in the right direction to choose the right filter even if the decision to bundle the functionality later is made.

**Comment by ngortheone** [comment]
Slightly offtopic, but @poolpOrg - what is the difference between extras repo and addons? It feels like they both serve similar purpose.

**Comment by poolpOrg** [comment]
the extras repo is going to bite the dust.

we're not quite there yet but it uses APIs that are slowly but surely being deprecated so it is in maintenance mode, we'll fix bug but no new features get committed there.

**Comment by poolpOrg** [comment]
I have updated the example for DKIM, the man page in master and portable branch removed mentions to dkimproxy and provide examples for filter-dkimsign and filter-rspamd instead.

**Comment by K14D** [comment]
First of all: Thanks for the great work!

I tried to use the filter-dkimsign according to the example in smtpd.conf(5). It does not work, because <domain> and <selector> are not "expanded" which results in "dkimsign: sh: cannot open domain: No such file or directory".

If I understood the example wrong and <domain> and <selector> is meant as placeholder in this context, this example is at least a little bit confusing.

**Comment by poolpOrg** [comment]
Hello,

The man page is still being worked on in the OpenBSD tree with the help from jmc@ it will not stay as is in the github mirror for long.
