### ISSUE TITLE
Question regarding config|subsystem|smtp-out + smtp-in (missing in 0.4?)

### ISSUE THREAD

**Issue by terminar** [OpenSMTPD/OpenSMTPD#1021]
Some question regarding the config|subsystem|smtp-out and config|subsystem|smtp-in events.

It took some time to realize that but (maybe due to using 0.4 of the filter api with OpenSMTPD 6.6.0p1 on FreeBSD 12.1) they are not sent at my installation. That leads to the problem that e.g. the current master of filter-eventlog is not working due to this code fragment:

	while ((linelen = getline(&line, &linesize, stdin)) != -1) {
		line[strcspn(line, "\n")] = '\0';
		if (strcmp("config|subsystem|smtp-in", line) == 0)
			smtp_in = 1;
		if (strcmp("config|subsystem|smtp-out", line) == 0)
			smtp_out = 1;
		if (strcmp("config|ready", line) == 0)
			break;
	}

smtp_in or smtp_out is never set because the lines are not sent. I've fixed it at my installation removing the check and just sending the register when receiving "config|ready". The same happens to my archive filter - i had to just sent the register without checking for config|subsystem.
Maybe this situation should be intercepted in filter-eventlog (or documented that this filter will only work with 0.5+. (?)**

**Comment by poolpOrg** [comment]
I'm unsure what to do about this ticket :-/

filter-eventlog is a personal piece of code which doesn't really have a release, I wasn't even aware someone else was using it besides me, which is why it doesn't have a README, doesn't have a tag, doesn't have a package on OpenBSD, etc... if it can help you I'll tag the latest version that worked with 6.6.0p1 so it can be used as a reference ?

If it is useful to others I can make a real release of it, it just doesn't exist today.

As for the API, until we release API version 1.0, the API is a moving target with no backward compatibility which is why it was released as "experimental". People writing filters should either wait for the first stable version of the API, or be ready to deal with API changes that may occur every now and then. I did that for filter-rspamd, filter-greylist, filter-senderscore but I didn't really care about filter-eventlog because it does not have a formal release.

**Comment by terminar** [comment]
> I'm unsure what to do about this ticket :-/

It was just regarding a question to unterstand the config* stufe correct (you answered it sort of - API is in flux and that may happen), second (about filter-eventlog) was just informational, i wasn‘t aware if that „bug“ is known and of interest to you.
Nevermind.
