### ISSUE TITLE
Documentation for OpenSMTPd LDAP Newer Syntax

### ISSUE THREAD

**Issue by sissieadmin** [OpenSMTPD/OpenSMTPD#1043]
Hey all.

Im looking at integrating OpenSMTPd and Dovecot with LDAP. It looks like Opensmtpd has had support for LDAP before but there is no recent documentation for LDAP support in the new syntax.

I was hoping to get directions or help get some documentation together for such integration.

Any sources out there?

**Comment by poolpOrg** [comment]
Hello,

Please use the mailing list for such questions as the issue tracker is for bugs and feature requests.

To answer your question, the new syntax had no impact whatsoever on the way LDAP is supported since it is a third party extension with its own configuration file. The ldap add-on comes with its man page and there are people on the mailing list who use the LDAP add-on.
