### ISSUE TITLE
Support matching for process-based filters

### ISSUE THREAD

**Issue by ryanakca** [OpenSMTPD/OpenSMTPD#1052]
All non-process-based filters support matching based on conditions. For uniformity, it would be nice if process-based filters (`filter filter-name proc proc-name` or `filter filter-name proc-exec command`) also supported matching.

As an example use case, I would like to be able to write the following in `smtpd.conf`:
```
filter dkimsign-rak-ac proc-exec "filter-dkimsign -d rak.ac -s may2018 -k /etc/mail/dkim/rak.ac.key" match mail-from regex ".*@rak.ac"
filter dkimsign-debian-org proc-exec "filter-dkimsign -d debian.org -s rak -k /etc/mail/dkim/debian.org.key" match mail-from regex ".*@debian.org"

filter dkimsign chain dkimsign-rak-ac dkimsign-debian-org

listen on lo0 filter dkimsign
```

(I'm using [filter-dkimsign](http://imperialat.at/dev/filter-dkimsign/).)

**Comment by poolpOrg** [comment]
Hello @ryanakca,

Unfortunately this can't be done because builtin filters and process filters work in very different ways and this parameter matching is unambiguous for builtins but ambiguous for process filters.

A major difference between both is that builtin filters are installed by the configuration which determines what events the filter is registered to and what parameters are valid for an event, whereas process filters register their events dynamically. The configuration file can't know in advance if a filter will even register an event post-`mail-from` or if it will register multiple events that will be conditional to `mail-from`.

In your dkimsign example, this sort of works because you always have a `mail-from` which you will only match once and do a simple thing with, but imagine the case of filters where you do all of your work before `mail-from` (ie: dnsbl taking a decision before `mail-from`), filters where you start crafting stuff before `mail-from`(ie: rspamd which starts building a request from the time you connect) or even random filters that may match different `mail-from` at different phases (ie: match mail-from to accept/reject a sender upon MAIL FROM, then match mail-from upon RCPT TO for tagging mail differently based on a sender / recipient tuple).

There are also other reasons why this will not work but the bottom line is that any phase-specific configuration in a process filter should be part of that filter configuration as filters operate as black boxes from OpenSMTPD point of view.

**Comment by ryanakca** [comment]
Thanks Gilles for the detailed explanation (and for all of your hard work).
