### ISSUE TITLE
Build failing on gentoo musl

### ISSUE THREAD

**Issue by lanodan** [OpenSMTPD/OpenSMTPD#1065]
When building opensmtpd with musl I either get:

- [build-warning.log](https://github.com/OpenSMTPD/OpenSMTPD/files/4705859/build-warning.log): an implicit declaration of `strnvis` and lack of #define for `VIS_*`
- [build-Werror.log](https://github.com/OpenSMTPD/OpenSMTPD/files/4705860/build-Werror.log): with setting `-Werror=implicit-function-declaration` (common workaround auto*hell) I get an error with `fparseln` being undeclared.

**Comment by poolpOrg** [comment]
I'll have a look

**Comment by c-14** [comment]
I started investigating this because I have the same problem on musl.
From what I can see, the problem seems to be in the configure script on musl.

On glibc (where it builds successfully), configure searches for the vis.h and tests linking against strnvis, fails both checks and uses the openbsd-compat headers/libs.
```
checking vis.h usability... no
checking vis.h presence... no
checking for vis.h... no
[..]
checking for strnvis... no
```

In particular, when checking for strnvis configure tests linking with the following command.
```
configure:13570: checking for strnvis
configure:13570: gcc -o conftest -g -O2  -fPIC -DPIC   conftest.c -lcrypt -lresolv  >&5
conftest.c:168: error: undefined reference to 'strnvis'
collect2: error: ld returned 1 exit status
```

On musl however, configure also fails to find vis.h but manages to correctly link against strnvis.
```
checking vis.h usability... no          
checking vis.h presence... no                     
checking for vis.h... no
[..]
checking for strnvis... yes
```

After checking the config.log, I noticed that when testing for strnvis support (and several other libs) it additionally links against libbsd (which is installed on the system) and therefore finds a working strnvis implementation.
```
configure:13570: checking for strnvis
configure:13570: gcc -o conftest -g -O2  -fPIC -DPIC   conftest.c -lfts -lbsd  >&5
/usr/lib/gcc/x86_64-gentoo-linux-musl/9.3.0/../../../../x86_64-gentoo-linux-musl/bin/ld: /usr/lib/gcc/x86_64-gentoo-linux-musl/9.3.0/../../../libc.so: warning: This function cannot be safely ported, use getline(3) instead, as it is supported by GNU and POSIX.1-2008.
configure:13570: $? = 0
configure:13570: result: yes
```

Compilation of opensmtpd then fails because HAVE_VIS_H is unset so smtpd/mda.c includes bsd-vis.h from openbsd-compat which has a `#if !defined(HAVE_STRNVIS) || defined(BROKEN_STRNVIS)` header guard around it. Because HAVE_STRNVIS is defined by confiure the header is skipped and neither strnvis nor the VIS_* defines are ever defined.

I'm not very good with autoconf so I'm not sure why configure adds libbsd to LIBS, so I'm not sure what to do on that front. Maybe adding an explicit libbsd check to the autoconf scripts would get it to add the library and the include paths so both HAVE_VIS_H and HAVE_STRNVIS would get defined and it would use libbsd's implementation. As a quick workaround, I tried changing the inclusion guard in openbsd-compat/vis.h to `#if !defined(HAVE_VIS_H) || defined(BROKEN_STRNVIS)` and that seems to fix compilation as well though it does warn about several other implicitly defined functions (strmode, strtonum, inet_net_pton, etc) but linking succeeds (presumable because of the -lbsd in LIBS).

I've uploaded a complete copy of the failing config.log in case it'll be helpful to debug with [config.log](https://gist.github.com/c-14/642d330eea86fc0dc17e591458a9b0f5)

**Comment by lanodan** [comment]
btw I noticed that Alpine Linux (musl system) managed to compile OpenSTMPd, no idea how it ends up working for them and not us.

**Comment by orbea** [comment]
These PRs should fix all of the issues. https://github.com/OpenSMTPD/OpenSMTPD/pull/1195 https://github.com/OpenSMTPD/OpenSMTPD/pull/1196 https://github.com/OpenSMTPD/OpenSMTPD/pull/1198

**Comment by orbea** [comment]
@lanodan and @omar-polo This should be fixed now.

**Comment by omar-polo** [comment]
Yeah, this should be fixed now.  Before I couldn't build on void (with musl), now it works fine with both `--with-libbsd` (the default) and `--without-libbsd`.  Builds with `--with-Werror` still fails, but for other reasons.

just FYI: before the build could be done by forcefully using libbsd via `./configure CFLAGS="$(pkg-config --cflags libbsd-overlay)" LDFLAGS="$(pkg-config --libs libbsd-overlay)"` or equivalent.  The issue was some interaction between early checks and some later ones that pulled in libbsd; now we look for libbsd only at the start, avoiding most of these troubles.

**Comment by omar-polo** [comment]
I believe this is fixed.  I've been building opensmtpd countless of times on alpine and void linux in these last weeks without issue of any sort, so I'll close this.

Feel free to reopen in case the issue persist.  Thanks for reporting!
