### ISSUE TITLE
[FR] Support for more password algorithms

### ISSUE THREAD

**Issue by owenthewizard** [OpenSMTPD/OpenSMTPD#1072]
Would be nice to have a config option for password algorithm selection, what are your thoughts?

**Comment by poolpOrg** [comment]
OpenSMTPD relies on the host system's `crypt(3)`, `bsd_auth(3)` or `pam(3)` so the password algorithm is really whichever is provided by the host system. This is so that any algorithm supported by the system is supported by OpenSMTPD out of the box but also so that you can extend by writing `bsd_auth(3)` or `pam(3)` modules if you want to use a custom method without having to pour that code in the daemon.
