### ISSUE TITLE
Document filters protocol changes between versions 0.4 and 0.5

### ISSUE THREAD

**Issue by palant** [OpenSMTPD/OpenSMTPD#1096]
I wasted way too much time implementing a filter. Turned out, `smtpd-filters(7)` man page only applies to the current OpenSMTPD using filters protocol 0.5, yet I’m running OpenSMTPD 6.6.4 using filters protocol 0.4. The older version expects session ID and token in reverse order, and there will be no warning whatsoever if you aren’t aware of that, mail processing simply hangs.

I think that `smtpd-filters(7)` should document differences to past protocol versions. Otherwise filter implementors won’t know which versions their filter is compatible with.

Also, such breaking changes shouldn’t be implemented without flagging compatibility issues. In this particular case, the relevant code path is here:

https://github.com/OpenSMTPD/OpenSMTPD/blob/a6a39cb0cb6ee72d194f84d6763997df7e0c0bf3/usr.sbin/smtpd/lka_filter.c#L655-L657

It shouldn’t merely ignore unknown session IDs – it should check whether the token is a valid session ID. In that case it should produce a warning for the filter implementor, this filter needs updating.

**Comment by palant** [comment]
Stumbled upon another similar scenario: documentation lists `message-id result address` as `tx-mail` parameters, yet the order was `message-id address result` in filters protocol 0.4 apparently.

**Comment by poolpOrg** [comment]
I'll submit a documentation change.

Note that the protocol version has not reach stable yet and is subject to changes, there was a decision taken not to be too strict in flagging incompatibilies and supporting backward compat until 1.0 is reached as it would otherwise be too heavy of a process at this point.

Until 1.0 is out, filter API may break any day, docs may be out of sync, the API is reserved for developers willing to help stabilize things, not for developers willing to be mere consumers.

**Comment by poolpOrg** [comment]
Sorry, I misunderstood the issue.

I thought there was an inaccurate description of the 0.5 protocol and that you also wanted protocol changes to be documented but only the latter is requested.

As I wrote above, the protocol is in development at this point and multiple breaking changes can happen within the same release cycle which is why it was decided that tracking all changes between protocol versions is too much effort at this point. It already happened that a field was being "tested" to see how convenient it was, and if everyone of these experiments was documented, it would slow down considerably the release of the first stable protocol release.

The protocol is not stable and people should only use it if they want to experiment, are able to adapt to changes and willing to support these breaking changes as they're discovered. There should not be much shifting of fields at this point but it's likely new events will be generated, just like its possible the format of some fields will change still.

What was decided is that the first stable release of the protocol, 1.0, will be the starting point for backward compatibility and documenting breaking changes.
