### ISSUE TITLE
Documentation Clarification - opensmtpd-extras

### ISSUE THREAD

**Issue by davidfavor** [OpenSMTPD/OpenSMTPD#1118]
Looking at build details, looks like at some point all the libexec/opensmtpd/* code moved to mainline to be built as part of main, package, rather than having a separate package.

For example, building latest (opensmtpd-6.8.0p2 as of today), looks like all extras are already included.

Someone let me know if this is correct.

Thanks!

**Comment by poolpOrg** [comment]
Absolutly not 😄Le 26 déc. 2020 18:48, David Favor <notifications@github.com> a écrit :
Looking at build details, looks like at some point all the libexec/opensmtpd/* code moved to mainline to be built as part of main, package, rather than having a separate package.
For example, building latest (opensmtpd-6.8.0p2 as of today), looks like all extras are already included.
Someone let me know if this is correct.
Thanks!

**Comment by davidfavor** [comment]
Thanks.

I do see now all the libexec/table-* tools are missing.

So then for opensmtpd-6.8.0p2 (latest) looks like maybe opensmtpd-extras-6.7.1 is the latest extras version to build.

Let me know if this is correct.

**Comment by poolpOrg** [comment]
Yes this is correct
