### ISSUE TITLE
Missing VRFY (RFC non-conformance)

### ISSUE THREAD

**Issue by sjbronner** [OpenSMTPD/OpenSMTPD#1146]
RFC 5321 contains the following text about the VRFY command.

> 3.5.3.  Meaning of VRFY or EXPN Success Response
> 
>    As stated elsewhere, implementation (in the sense of actually validating
>    addresses and returning information) of VRFY and EXPN are strongly
>    recommended.  Hence, implementations that return 500 or 502 for VRFY are not
>    in full compliance with this specification.

> 4.5.1.  Minimum Implementation
> 
>    In order to make SMTP workable, the following minimum implementation
>    MUST be provided by all receivers.  The following commands MUST be
>    supported to conform to this specification:
> 
>       EHLO
>       HELO
>       MAIL
>       RCPT
>       DATA
>       RSET
>       NOOP
>       QUIT
>       VRFY

The command VRFY is discussed quite a bit throughout the RFC. But these two quotes are the most clear about its implementation being mandated. All mentions of VRFY taken together, it becomes clear that RFC 5321 considers SMTP to be (slightly) broken without VRFY.

Here is how OpenSMTPD 6.8.0p2 responds:

```
 % nc 127.0.0.1 25
220 tucson ESMTP OpenSMTPD
vrfy sb@localhost
500 5.5.1 Invalid command: Command unrecognized
```

Since OpenSMTPD bills itself as an RFC-compliant MTA, I am making the case for the implementation of VRFY. If this idea meets with approval, I would be happy to start work on that and submit a pull request.

**Comment by poolpOrg** [comment]
Hello,

You should not assume that OpenSMTPD is _RFC-compliant_ as it is really _RFC-compliant for the most part_ and compliance is sacrificed when it does not break interoperability with other MTA and there's enough evidence that compliance would cause more issues than it solves. There aren't many of these decisions not to follow the RFC, but there are still a few.

In the case of VRFY and EXPN, it is a deliberate choice for instance.

VRFY and EXPN both have a history of being abused to scan local user accounts and provoke DoS attacks by abusing costly aliases/virtual expansion loops. As a result, at least since mid-90s, the general consensus was that they should be disabled by default, leading to these being unreliable for clients which stopped relying on them.

I don't see a good rationale to implement them just for RFC compliance given that they are risky and not used by any modern client.

I discussed this with @ericfaurot and there's strong objections upstream so this will just not happen and fall in the bucket of unresolvable non-compliance.

**Comment by sjbronner** [comment]
Hi @poolpOrg,

thank you very much for your explantion. And I completely get the point. Previously, I had looked through the website and the documentation with the source code to see if I could find mention of a decision not to follow the RFC in certaint points, but I didn't find any.

How would you feel about adding a page https://www.opensmtpd.org/rfc-choices.html ? I, personally, would value knowing this and other deliberate choices not to follow the RFC and the reasons behind those choices while evaluating the software.

I also saw the following text in RFC 5321, suggesting that 502 might be a more appropriate return code for VRFY than 500:

```
4.3.2.  Command-Reply Sequences

   500  For the "command line too long" case or if the command name was
      not recognized.  Note that producing a "command not recognized"
      error in response to the required subset of these commands is a
      violation of this specification.

   [...]

   Specific sequences are:

      [...]

      VRFY

         S: 250, 251, 252
         E: 550, 551, 553, 502, 504
```

It seems that not implementing VRFY is "not in full compliance with this specification", but that returning 500 to it is "a violation of this specification", which is much stronger. Changing this to 502 should not add any vulnerability to OpenSMTPD, should it?

**Comment by poolpOrg** [comment]
> How would you feel about adding a page https://www.opensmtpd.org/rfc-choices.html ? I, personally, would value knowing this and other deliberate choices not to follow the RFC and the reasons behind those choices while evaluating the software.

This is a very good idea, I'll discuss this with upstream

> It seems that not implementing VRFY is "not in full compliance with this specification", but that returning 500 to it is "a violation of this specification", which is much stronger. Changing this to 502 should not add any vulnerability to OpenSMTPD, should it?

Nope, that is a sensible change to suggest, will talk with upstream, thanks !
