### ISSUE TITLE
bunch of implicit-function-declaration failures (building on alpine linux with -Werror=implicit-function-declaration)

### ISSUE THREAD

**Issue by nekopsykose** [OpenSMTPD/OpenSMTPD#1217]
without libbsd:  

```
/home/demon/src/aports/community/opensmtpd/src/opensmtpd-7.3.0p0/openbsd-compat/inet_net_pton.c:235:24: error: implicit declaration of function 'strtonum'; did you mean 'strtoul'? [-Werror=implicit-function-declaration]
  235 |                 bits = strtonum(sep, 0, 128, &errstr);
      |                        ^~~~~~~~
      |                        strtoul
```

config.h detects HAVE_STRTONUM for some reason though, not sure why

with libbsd:

```
/home/demon/src/aports/community/opensmtpd/src/opensmtpd-7.3.0p0/usr.sbin/smtpd/util.c:482:16: error: implicit declaration of function 'res_hnok' [-Werror=implicit-function-declaration]
  482 |         return res_hnok(s);
      |                ^~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [Makefile:1128: ../../usr.sbin/smtpd/smtpd-util.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /usr/include/bsd/sys/cdefs.h:47,
                 from /usr/include/bsd/inttypes.h:37,
                 from /usr/include/netinet/in.h:9,
                 from /usr/include/netdb.h:9,
                 from ../../openbsd-compat/includes.h:59,
                 from ../../usr.sbin/smtpd/parse.y:25:
/usr/include/sys/cdefs.h:4:2: warning: #warning usage of non-standard #include <sys/cdefs.h> is deprecated [-Wcpp]
    4 | #warning usage of non-standard #include <sys/cdefs.h> is deprecated
      |  ^~~~~~~
/home/demon/src/aports/community/opensmtpd/src/opensmtpd-7.3.0p0/usr.sbin/smtpd/parse.y: In function 'yyparse':
/home/demon/src/aports/community/opensmtpd/src/opensmtpd-7.3.0p0/usr.sbin/smtpd/parse.y:340:22: error: implicit declaration of function 'res_hnok' [-Werror=implicit-function-declaration]
  340 |                 if (!res_hnok($2)) {
      |                      ^~~~~~~~
```

similar thing, detects that as HAVE_ but that isn't true

full config.log (uploaded too big):  https://img.ayaya.dev/mvD86twS7t2t

**Comment by omar-polo** [comment]
Hello, thanks for the report.

The problem is due to a wrong ordering of things in the configure: it first looks for `libasr` and only then checks the functions.  This bites us because it finds the symbols in libasr (which has its own compat layer), but prototypes are not provided in the standard headers.  There's a similar issue on FreeBSD with the mis-detection of recallocarray which has very bad consequences.

By the way, please consider building with `--with-bundled-libasr` and/or uninstall libasr entirely.  It was discontinued: https://github.com/OpenSMTPD/libasr/commit/05b8bf7d480c25195b365552f9ed6021cd0a68e3, we'll keep up-to-date only the bundled version.

 >#warning usage of non-standard #include <sys/cdefs.h> is deprecated

this is from libbsd, I don't think there's anything we can do about.  Nothing in OpenSMTPD includes cdefs.h anymore.

**Comment by nekopsykose** [comment]
https://github.com/OpenSMTPD/OpenSMTPD/commit/11c6e33f5571a964cd5fb5f5d0fc16e439d0dd4e fixes it perfectly. thanks a lot :)  

> By the way, please consider building with --with-bundled-libasr and/or uninstall libasr entirely.  

sure, i'll do that. thanks for the heads up!

>> #warning usage of non-standard #include <sys/cdefs.h> is deprecated
> this is from libbsd, I don't think there's anything we can do about. Nothing in OpenSMTPD includes cdefs.h anymore.  

yeah, this part isn't related at all, just part of libbsd warnings.
