### ISSUE TITLE
changed table format disabled unified "credentials" file with dovecot?

### ISSUE THREAD

**Issue by ethael** [OpenSMTPD/OpenSMTPD#1266]
Hello,

after 7.5->7.6 upgrade smtpd won't start because of error in table files:

```
smtpd[4219]: info: OpenSMTPD 7.6.0-portable starting
smtpd[4228]: credentials[4228]: warn: table-api: imsg_get: Numerical result out of range
smtpd[4222]: lookup: table-proc: unexpected EOF during handshake
smtpd[4219]: warn: parent -> lka: imsg_read: Connection reset by peer
smtpd[4219]: smtpd: exiting: Connection reset by peer
```

I use single credentials file for both dovecot and smtpd with syntax like so:

`turbo@example.com:passwordhash:vmail:2000:2000:/var/vmail/example.com/turbo::userdb_mail=maildir:/var/vmail/example.com/turbo`

My guess is, that with new tables protocol, this syntax is not possible anymore and I need to use:

`turbo@example.com     passwordhash`

If so, is there any good way to keep one pass file for both services after upgrading to 7.6?

**Comment by omar-polo** [comment]
If by any chance you're using OpenBSD, please delete the deprecated package wiht `pkg_delete opensmtpd-extras` , install the new one with `pkg_add opensmtpd-table-passwd` then restart smtpd.

**Comment by Kusoneko** [comment]
Not OP but:

> If by any chance you're using OpenBSD, please delete the deprecated package wiht `pkg_delete opensmtpd-extras` , install the new one with `pkg_add opensmtpd-table-passwd` then restart smtpd.

Thank god for this message, I only just noticed my personal email server stopped working and I was at a loss since everything worked just fine under OBSD 7.5.

> ```
> smtpd[4228]: credentials[4228]: warn: table-api: imsg_get: Numerical result out of range
> smtpd[4222]: lookup: table-proc: unexpected EOF during handshake
> ```
> 
> (ok, it's not very obvious, but that's the indication we have that the `table-passwd` executable you're using doesn't speak the right protocol).

It is indeed not a very clear message, in my experience every time I've encountered the specific words "unexpected EOF during handshake", I'm usually led to believe it's an openssl/libressl-related issue, so I spent a good 45 minutes looking if maybe i had:
- a broken acme-client config suddenly?
- dns issues due to some kind of ssl/tls failure?
- etc
until I realized, all of those worked just fine, and dovecot was still working just fine so the issue was strictly smtpd, and a search somehow landed me here (note to self, never search for "process name: error message" since apparently some operating systems include the pid after the process name, which leads to not finding any results)

**Comment by omar-polo** [comment]
@Kusoneko I'm sorry :(

We try to avoid doing disruptive changes, but in some cases we have no other options, and this was on of such cases.  The previous was a binary protocol and the new one it's text-based (like the one for filters), so we don't have a chance to do versioning here.  The "unexpected EOF" message was also intended towards external tables developers, not really for end users.

I'm wondering if the the changelog should have had a stronger text, and for OpenBSD users in particular since it was noted on the [Upgrade guide 7.5 -> 7.6](https://www.openbsd.org/faq/upgrade76.html) under "Configuration and syntax changes" along with the OpenBGP change and the sysupgrade one.

**Comment by ethael** [comment]
@omar-polo thank you for quick response. I tried to upgrade on 21.10.2024. In that time I also checked if there was new release for extras, and there wasn't and repo was still active. Looks like it was marked as deprecated next day. Bad luck.

I tried to use table-passwd release 1.0.1 from the dedicated repo as adviced, but it failed to compile with error: 

`sys/tree.h No such file or directory`

The machines runs Debian, so I first installed libbsd-dev, but that didn't fix the build error. 
Then I manually compared the repo files and files in 1.0.1 release tar ball, and I found out, that the tarball is missing "tree" directory and "err.h" in the "openbsd-compat" folder. After I manually copied the missing files from the github repo to the unpacked release tarball, all went smooth and 7.6 is up and running.

Thanks a lot for your support.

**Comment by omar-polo** [comment]
@ethael ouch, sorry for missing those files and thanks for spotting the issue.  I'll open a dedicate issue on the other repository just to track it correctly, but I'll fix it as soon as possible and make a new release for the tables-* (it's likely that I made the same mistake on other tables as well :/)

**Comment by Kusoneko** [comment]
> @Kusoneko I'm sorry :(
> 
> We try to avoid doing disruptive changes, but in some cases we have no other options, and this was on of such cases. The previous was a binary protocol and the new one it's text-based (like the one for filters), so we don't have a chance to do versioning here. The "unexpected EOF" message was also intended towards external tables developers, not really for end users.
> 
> I'm wondering if the the changelog should have had a stronger text, and for OpenBSD users in particular since it was noted on the [Upgrade guide 7.5 -> 7.6](https://www.openbsd.org/faq/upgrade76.html) under "Configuration and syntax changes" along with the OpenBGP change and the sysupgrade one.

Oops, my bad then, I haven't actually read the upgrade page since I first started using OBSD with 7.1 I believe? This was the first time I had something break following an upgrade. On the other hand, I don't think I'd have realized with the message there at that time that that was the issue -- I've had this email setup for several years now, mostly based on a few guides I've found all over the internet (possibly from you as well as I recall seeing your username at some point during my OBSD mail server adventures?) so "table protocol changed", even with the example below that states the exact solution to this issue without actually saying it'd fix the issue might not have helped since my memory of how it's set up and what it uses is a little lost due to how long ago it was.

On one hand I'd be tempted to say that a post-upgrade message saying things like "manual intervention needed: smtpd: remove opensmtpd-extras and replace with corresponding opensmtpd-tables-* package" so you see the issue from within the server might help, but then again, I also don't often use the OBSD mail program as I don't particularly understand how to use it properly, and I think that's where those messages would end up, likely, and since I'm currently only using OBSD for my servers rather than daily driving it as a desktop OS, that makes the willingness to learn it through an ssh session on the few times a year I have to ssh into any of my servers to run syspatch/sysupgrade and pkg_add -u not very high, which would also be my bad, I guess. I would say that even though OpenBSD is clearly more intended towards powerusers and developers who know what they're doing, I'd say giving more interest to the project by attracting more users by being more user friendly would not be a bad idea. But that is all an unrelated off-topic issue, I guess.

**Comment by omar-polo** [comment]
> Oops, my bad then, I haven't actually read the upgrade page since I first started using OBSD with 7.1 I believe? This was the first time I had something break following an upgrade.

We try to avoid breaking existing configurations if possible, and in fact this is probably the first "break" of any sort since the change of the grammar in 6.something.

>  so "table protocol changed", even with the example below that states the exact solution to this issue without actually saying it'd fix the issue might not have helped since my memory of how it's set up and what it uses is a little lost due to how long ago it was.

My main takeaway from this is that I needed anticipate this kind of situation and provide better error messages, at least.

I've changed the release notes on github to be more explicit and also to link to the removal of the OpenSMTPD-extra repositories, but I should have done it from the start, too.

> On one hand I'd be tempted to say that a post-upgrade message saying things like "manual intervention needed: smtpd: remove opensmtpd-extras and replace with corresponding opensmtpd-tables-* package"

Actually `pkg_add -u` should have printed something alongside that text since the `opensmtpd-extras-*` packages are marked as obsoleted by the individual packages `opensmtpd-table-*`.  I don't blame you, I'm starting to realize that very few people actually notice `pkg_add` messages.  There's some UI to improve there too it seems.

> I would say that even though OpenBSD is clearly more intended towards powerusers and developers who know what they're doing, I'd say giving more interest to the project by attracting more users by being more user friendly would not be a bad idea.

I don't like to think of it as a "poweruser OS" (whatever that means.)  While we try to adhere to a certain kind of style for the overall system, and it's true that we don't do a lot of handholding, believe me we don't want to make things harder on purpose!  We've given a lot of thought on how to handle this change.

My initial proposal was to silently substitute the `opensmtpd-extras-*` packages with the new ones, but it was a bit fragile and annoying to maintain both for us and for the end users.  (another error was to clam together so many tables in a single package, but who would have thought at the time?)

So we decided instead to just deprecate the old packages with release notes for both the portable project and OpenBSD.  It was easier on the packages side and avoided to install unneeded stuff automatically on users' systems.

Since I've seen also a few other people being hit by this (also a few developers), I think the process could have been better though.  Note taken, I'll try to improve :)

> But that is all an unrelated off-topic issue, I guess.

An honest feedback is hardly off-topic :)

Thank you!
