### ISSUE TITLE
HaProxy PROXY Protocol

### ISSUE THREAD

**Issue by vr** [OpenSMTPD/OpenSMTPD#164]
Hello,

I would like to use HAProxy load balancer in front of OpenSMTPD, and so I would like to know if the PROXY Protocol http://haproxy.1wt.eu/download/1.5/doc/proxy-protocol.txt could be implemented in OpenSMTPD, like it is in Postfix ? 
For more information :
http://blog.exceliance.fr/2012/06/30/efficient-smtp-relay-infrastructure-with-postfix-and-load-balancers/
http://permalink.gmane.org/gmane.comp.web.haproxy/8881

**Comment by FreakyPenguin** [comment]
I might be interested in taking a stab at this. First I'd like to figure out though how much effort this might be (I'm not familiar with the opensmtp codebase) and if this the right time to look into this (given that filter support is being revamped). Does anyone have any pointers/comments/suggestions before I blindly try to hack away at this?

Thanks :)

**Comment by poolpOrg** [comment]
I don't know if it's going to be much effort because I've never had a look.

Now is an okay time to work on it, as long as the code is isolated, it won't be hard to adapt to filters later, I suggest you communicate with us as you start hacking on it so that you don't realize too late we're making a change that will impact you ;-)

**Comment by FreakyPenguin** [comment]
I started hacking on this a bit over the weekend [here](https://github.com/FreakyPenguin/OpenSMTPD/tree/feature-proxy) ([current diff](https://github.com/FreakyPenguin/OpenSMTPD/compare/portable...FreakyPenguin:feature-proxy). I haven't done any sort of in depth testing on the code and there are definitely some kinks to work out, but the basics seem to be working.

This only implements the core functionality of the binary version of the protocol PROXYv2 as described [here](http://www.haproxy.org/download/1.8/doc/proxy-protocol.txt). The basics are pretty simple, before the proxy starts forwarding it injects a header that is basically an abstract version of struct sockaddr_storage, informing the receiver about the real endpoint of the connection. The protocol also supports some additional attributes, such as flags telling you whether it terminated a TLS connection or if the client provided a valid client certificate, but I currently ignore all of those (and I'm not sure those are really useful here).

My implementation modifies `smtpd/smtp.c` so that it calls into the proxy code for every connection that's accepted from a listener tagged with the proxy flag (which can be set in the config). The proxy code then waits for and processes the header, generates an updated `sockaddr` and invokes a provided callback to indicate that the connection is ready, after which regular smtp processing continues.

Overall I'm not sure if this is really the cleanest way to hook this code in, but it keeps the proxy code mostly separated out, but it does require splitting up the code in smtp.c to separate the parts that can only be done after the proxy processing is complete.

The other thing I needed to modify is that the proxy code passes a `struct io*` on it's callback, which will be passed through to `smtp_session()`. This seems necessary because the proxy code might have already received more than just the PROXY header, which will then be buffered in that io, so this needs to be preserved and passed along.

I'd be happy for input/questions/suggestions on any of these points. I'll hopefully get around to testing and cleaning this up some more in the next couple of days.

**Comment by jdelic** [comment]
> This only implements the core functionality of the binary version of the protocol PROXYv2 as described here.

I have only one suggestion, currently: 

In keeping with the "spirit of SMTP", I would love to see proxy protocol version 1 support in the final implementation. Simply so that a proxy endpoint can also be used with `telnet` and a human-readable protocol representation for easy debugging of SMTP+PROXY sessions. I hope that's not too much additional work.

**Comment by jdelic** [comment]
@poolpOrg 
Since @FreakyPenguin is actively working on this issue, can we reopen this ticket?

@FreakyPenguin 
Another suggestion: It would be awesome if you'd fork this repo and opened a PR for your changes when you have the time.

**Comment by poolpOrg** [comment]
@ericfaurot care to help me review this ?

**Comment by FreakyPenguin** [comment]
@jdelic I'll look into adding v1 support as well. It should be pretty straight forward. I did not really think about testing/debugging, so I thought v2 should be enough and I could avoid writing the text parsing code. ;-)

I also opened a PR now, I just wanted to avoid anyone merging this prematurely before I have a chance to do some testing.

**Comment by poolpOrg** [comment]
So this took a while but as you could see there's been a lot of changes to our code recently and they actually made it easier for me to work on your PR.

The PR as is was broken obviously with all the changes and there are a few changes I made here and there but it is mostly the same as you submitted.

There are still a few shortcomings that need to be fixed before it gets committed, for instance the reverse address doesn't get carried so the helo response is weird:

    220 laptop.home ESMTP OpenSMTPD
    ehlo l
    250-laptop.home Hello l [], pleased to meet you

Also i made the keyword proxy-v2 instead of proxy because it bit me ... but I think this might very well make it to the next release.

Work in progress and changes are visible in the 'proxy' branch on github.

**Comment by poolpOrg** [comment]
reassigning the ticket to me as I'm doing the integration ;-)

**Comment by poolpOrg** [comment]
Done with this, however I'm not confident enough to merge so close to 6.4.0 so it will be part of the 6.5.0 release.
