### ISSUE TITLE
Allow OpenSSL options to be specified

### ISSUE THREAD

**Issue by edeln** [OpenSMTPD/OpenSMTPD#359]
OpenSSL lib allow to set specific options per SSL context, eg using SSL_CTX_set_options. This would help tuning connections with buggy remote relays.

Example: some malconfigured relays don't even relpy when opensmtpd send a TLS 1.2 client hello, causing MTA connection timeout. Using OpenSSL would help solving such problems (in this case using SSL_OP_NO_TLSv1_2, used for the -no_tls1_2 option of openssl s_client)

**Comment by sysfu** [comment]
I would like to re-open discussion on this issue for a different use case: In light of more vulnerabilities discovered in the TLSv1.0 protocol since Dec 2013, I no longer feel it provides acceptable security and would like a configuration option to disable support for it. Going even further, I would also like to be able to disable TLSv1.1, and force all incoming connections to use TLSv1.2.

Seeing as how this does not downgrade security, but rather upgrades it, I think it merits consideration.

Syntax could be something like dovecot's 10-ssl.conf option

```ssl_protocols = !SSLv2 !SSLv3 #!TLSv1```

**Comment by tdm4** [comment]
+1  I'd like this option too.
Seeing a lot of spammers connecting with TLSv1.0 now too.

**Comment by ArchangeGabriel** [comment]
Restricting to TLS 1.2 is easy actually. OpenSMTPD allows setting one SSL parameters: ciphers.

A line like `ciphers ECDHE+CHACHA20:ECDHE+AESGCM`. If you have an SSL lib with ARIA (OpenSSL 1.1.1+) or Camellia GCM, you can add those. If you have TLS 1.3, maybe you can add TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-256-GCM-SHA384:TLS13-AES-128-GCM-SHA256, but in the case of OpenSSL I believe they did split 1.3 ciphers setting to another command.
