### ISSUE TITLE
Multiple certs in CA file generates fatal error during startup

### ISSUE THREAD

**Issue by hrkfdn** [OpenSMTPD/OpenSMTPD#415]
To properly use certificates signed by STARTSSL a bundle of PEM encoded certificates must be used as the CA. However, this prevents smtpd from starting.

The following error occurs:
```
Jan 29 16:51:36 ira smtpd[4498]: info: OpenSMTPD 5.4 starting
Jan 29 16:51:36 ira smtpd[17762]: info: startup
Jan 29 16:51:36 ira smtpd[1333]: fatal: smtp: ssltree out of sync
Jan 29 16:51:36 ira smtpd[4482]: warn: mfa -> smtp: pipe closed
Jan 29 16:51:36 ira smtpd[7479]: warn: queue -> smtp: pipe closed
Jan 29 16:51:36 ira smtpd[26672]: warn: control -> smtp: pipe closed
Jan 29 16:51:36 ira smtpd[23895]: warn: lka -> queue: pipe closed
Jan 29 16:51:36 ira smtpd[999]: warn: mda -> queue: pipe closed
Jan 29 16:51:36 ira smtpd[6597]: warn: mta -> queue: pipe closed
Jan 29 16:51:36 ira smtpd[12810]: warn: scheduler -> queue: pipe closed
Jan 29 16:51:36 ira smtpd[17762]: fatal: msgbuf_write: Broken pipe
```

This happens with the OpenSMTPD version shipped with OpenBSD 5.4 as well as the latest release (5.4.1).

This is the related CA bundle: https://www.startssl.com/certs/ca-bundle.pem

**Comment by poolpOrg** [comment]
wow, I didn't see that I actually had answers to this year old ticket...

@hrkfdn: this is to verify the certificate presented to the server: either when a client sends a certificate (not mandatory unless you configure smtpd to require client certs) or when a peer server presents a certificate during a relay. It's not meant to be sent to a client.

I'll close this ticket which is about a crash since @hrkfdn reported that a snapshot has fixed the issue.

@crepererum if you feel clarifications needs to be done, please open a separate ticket describing what clarifications you'd expect and where, so it doesn't get lost.
