### ISSUE TITLE
ordering docs and/or parser limitation: recipient <foo> virtual <bar> (ok), virtual <bar> recipient <foo> (!ok)

### ISSUE THREAD

**Issue by toddfries** [OpenSMTPD/OpenSMTPD#440]
accept from any for domain <relayu> recipient ! <relayv> virtual { "@" = "error:421 Temporary Failure" } deliver to mda "cat > /dev/null"

thats ok

accept from any for domain <relayu> virtual { "@" = "error:421 Temporary Failure" } recipient ! <relayv> deliver to mda "cat > /dev/null"

thats not ok

105640 < __gilles> well it's currently strictlyu necessary because i was not done with the parser cleanup
105659 < __gilles> so i'd say it s a parser limitation to overcome

**Comment by poolpOrg** [comment]
Actually I was way too optimistic about "a parser limitation to overcome" it is more than that:

A rule is defined by a set of conditions (from, sender, for, recipient, tagged) as well as a lookup mappings (userbase, aliases/virtual).

They don't operate at the same level: while you can always set one or many conditions, the mappings can only be set depending on other factors and previous conditions.

That's why you can swap for / from / sender / recipient / tagged as much as you want but they must still be placed before the mappings.

To allow for swapping any parameter on a rule no matter what, it would require putting all the conditions / mappings / decisions at the same level, each one being applied no matter what other options are set, then applying a sanity check at the end of a rule to go through every option and see if it is compatible with the others.

This is pretty much a complete rewrite of how our parse.y works.

I personally don't think it's worth pouring ourselves that amount of work just so "virtual" can be used before "recipient", given that this ticket is > 1 year old and no one else has expressed any concern about it, I'll close as "wontfix".
