### ISSUE TITLE
expansion tokens within aliases / virtual / general table lookups

### ISSUE THREAD

**Issue by poolpOrg** [OpenSMTPD/OpenSMTPD#480]
It should be possible to use the %{foobar} tokens we use in ruleset expansion within aliases/virtual databases as well as part of the queries uses in table lookups.

Proposed by a user on our mailing-list, discussed slightly with eric@, we both agree it would be a nice feature.

**Comment by poolpOrg** [comment]
from @kusuriya in #471:

    Just that the API for tables and the like should accept expansion so if I wanted to make a table query for SQL for example I could go and do 
    SELECT * FROM Accepted_Domains_Table WHERE domain = %{rcpt.domain} or could so something more complex
    SELECT * From Users WHERE username = %{rcpt.username} AND domain =  {rcpt.domain}
    
    Having the expansions available to tables and the rest of the API would allow for more robust multi site configs.

**Comment by jdelic** [comment]
Just a thought: the implementation of this should use query parameters when `%{foobar}` is used in place of a parameter. The above syntax suggests string replacement and that would be bad security practice. It might be easier to provide additional configuration directives like

```sql
query_alias SELECT otheremail FROM myemailaddresses WHERE sender=?;
query_alias_parameters %{sender}
```

And just an observation since I'm using this in a multi-tenant setup:
Right now you can easily implement a lot of logic using stored procedures, which while an arcane interface, work well with the already provided parameters and interface. The only thing you don't have there is access to the rest of the envelope data, which would be nice.

**Comment by poolpOrg** [comment]
After a lengthy discussion with @ericfaurot, I have come to the conclusion that this is not only NOT doable but also a bad idea. Bear with me, this ticket has a happy ending.

Expansion tokens are MDA-restricted, they're currently used in the lookup process due to an early design error which is being worked on in #772 but they're going to be handled in the MDA layer, hopefully before OpenSMTPD 6.3, which means that the lookup process will not even get a chance to see them. This will solve the design issue AND provide additional security as a bonus.

So, expansion tokens cannot and will not be used for table lookups.
However... maybe what we need is to extend the table API so it provides a mechanism similar to the token expansion but that's only fed by trusted input.

**Comment by poolpOrg** [comment]
The expansion variables were completely revamped two releases ago, there is no way they can be used in lookups as they are simply no longer accessible outside the MDA layer which is not visible from the lookup layer.

A different mechanism may be possible but this will require a redesign of table API which is not a priority for the time being.

Closing this feature request as it will simply not happen as is.
