### ISSUE TITLE
Add SMTP-AUTH header (Patch)

### ISSUE THREAD

**Issue by milesbarry** [OpenSMTPD/OpenSMTPD#514]
Hi,

One thing that maybe of use to some is being able to identify who was responsible for sending the mail. I've written a little patch which will include a X-Auth: header. 

You enable it by adding "auth-header" to the listener.

Note I made this patch against the opensmtpd-5.4.4p1 source tarball.

The patch is here:

http://pastie.org/private/o6pdyflprmryriespt7wgg

**Comment by poolpOrg** [comment]
Ohai,

I see the value in this and I've considered adding it, however I'd like other people to see it and agree on the header and keyword before it gets in.

I'll point people to this ticket so they get a chance to provide ideas.

Meanwhile, it would be nice if you could:

1- adapt this patch to master or portable branch instead of the stable tarball
2- issue a pull request so it is easier for us to merge and for you to keep credit

Gilles

**Comment by achamo** [comment]
When I'm sending an email via smtp+auth I have this : 

> Received: from macareux.lan.achamo.net (unknown
> [IPv6:2001:470::0])
> (using SSLv3 with cipher DHE-RSA-AES256-SHA (256/256 bits))
> (No client certificate requested)
> (Authenticated sender: user@achamo.net)
> by baleine.achamo.net (Postfix) with ESMTPSA id 3CC13A024E
> for <blih@blih.eu>; Fri, 28 Nov 2014 08:12:56 +0100 (CET)

**Comment by poolpOrg** [comment]
mh, part of the Received line is nice yes, I actually had to check if we weren't already doing that because it seems more appropriate than a custom header

**Comment by kusuriya** [comment]
I love the idea and it seems to work on my test machines just fine. X-authenticated-user or x-auth are both defacto accepted headers for this as i recall so I am fine with x-auth. With this though it may be valuable to have the knob a bit verbose so it can be set to either say whether or not the user authed (true/false or yes/no) or the username (user@contoso.com) but its not particularly a show stopper.

**Comment by milesbarry** [comment]
Hi @kusuriya thanks for the thumbs up. It's a widely used header when the likes of anti-spam outbound services are implemented. Without it, the likes of mail channels and spam experts could have difficulty in identifying the sending user.

As to the name of the header, well perhaps the ability to select your own would be nicer. But personally I went with X-Auth.

Regarding the knob... have not seen that style implemented before, not to say that just knowing that the user has be authd with correct credentials does not have it's benefits.

All the best

**Comment by kusuriya** [comment]
That honestly is the cleanest method and I think that would make the most sense if we are sticking to RFCs. It really makes it clear who was the initial point of trust. But then I would also bring up the question since part of the intent of this header is so that applications that do spam control can consume it, and do we want to provide a user controllable method that would allow them to have it as a regular header instead in case they have an app that is just too dumb to parse the received header.

**Comment by poolpOrg** [comment]
I think we have a different point of view regarding what this header should accomplish, so let me clarify a bit :-)

To me it does not serve any purpose as an anti-spam method, its purpose is to provide a bit of additional information to help a postmaster either troubleshoot or trace back a mail to an authenticated user should he have to.

A spammer can always generate fake X-Whatever headers matching the user-part of an email address and spam the bulk of the internet so we should not take that use case into account when designing that feature. If an application wants to make use of this message aimed at a human, it should do the extra processing rather than causing the human to be confused.

The extra processing can either be on their side, or it could be implemented as a custom filter which detects this construct and inserts a X-Whatever header in the stream, I just don't think this should be part of the stock daemon.

**Comment by kusuriya** [comment]
Sorry if there was confusion on what I said. The header itself does not serve as a spam control, it serves as a method for spam control programs to check to see who actually sent the message and verify they have rights to send as the mail from address. That is one of the many uses this can and does have.

**Comment by milesbarry** [comment]
Guys, I didn't really consider this for the use of relaying. It's primary use is to identify the origin of the sender. So, for example say we've got an guy sending a mail from his homeuser@isp.com via smtp.isp.com:587 using Thunderbird. First thing I'd do is have that listener using mask-source, plus I'd have it add the X-Auth header.  Then once the mail has been accepted, it may be then sent via a smart host service which then will parse that X-Auth.

I personally wouldn't be using the auth-header on any other scenario than that. Also to some extent I would not want say @isp.com users login usernames being exposed. I'd expect the smart host service to then strip the X-Auth header off once they had the info they required.

Finally keep in mind if you want it in the received from, it's going to vanish with the mask-source....

**Comment by poolpOrg** [comment]
Finally keep in mind if you want it in the received from, it's going to vanish with the mask-source....

not at all, `mask-source` was also designed with the postmaster in mind, it's not removing the Received line but merely removing sensitive information from it while still allowing the human to analyze the routing and see the hop.

stripping the Received line completely would also require a filter

**Comment by zx2c4** [comment]
Wouldn't this whole thing be better implemented in a filter?

**Comment by poolpOrg** [comment]
Well, the whole header adding makes sense to be part of a filter that does headers manipulation, however I think providing the information for human consumption by a postmaster in the Received line is an improvement.

As far as the smtp_session is concerned, this is only a conditional iobuf_fprintf(), moving it to filters isn't going to make it simpler or more secure.

**Comment by poolpOrg** [comment]
Ok, so this discussion got to nowhere and I didn't want this to die so I took @milesbarry 's diff and adapted it to display authentication as part of the Received header when the `received-auth` option is passed to listen.

Basically:

    listen on all [...] received-auth

Will result in the following header when a user authenticates:

    Received: from l (localhost [127.0.0.1])
            by debug.poolp.org (OpenSMTPD) with ESMTPSA id ca28ec68
            TLS version=TLSv1/SSLv3 cipher=ECDHE-RSA-CHACHA20-POLY1305 bits=256 verify=NO auth=yes user=gilles
            for <gilles@poolp.org>;
            Fri, 30 Jan 2015 23:50:12 +0100 (CET)

While non-authenticated sessions will result in:

    Received: from L (localhost [127.0.0.1])
            by debug.poolp.org (OpenSMTPD) with ESMTPS id 32c4da6d
            TLS version=TLSv1/SSLv3 cipher=ECDHE-RSA-CHACHA20-POLY1305 bits=256 verify=NO auth=no
            for <gilles@poolp.org>;
            Sat, 31 Jan 2015 00:06:57 +0100 (CET)

The default behaviour is not display that information at all.

The diff is essentially the same as @milesbarry except for the smtp_session part so I will credit this to him when I generate the snapshot and in our next release mail.

This code is already committed to github so I'm closing the ticket, it'll be part of the snapshot I'll publish Sunday.
