### ISSUE TITLE
Include rc.d script for FreeBSD installation

### ISSUE THREAD

**Issue by sysfu** [OpenSMTPD/OpenSMTPD#524]
It would be nice if a /usr/local/etc/rc.d/smtpd service file would be installed on FreeBSD systems when building the portable version of OpenSMTPD from source.

I had been simply copying this file from the FreeBSD  OpenSMTPD package, but it is not working anymore with the latest snapshot. Please log this as a feature request.

**Comment by poolpOrg** [comment]
Nope, we won't do that.

We don't provide any "control" files for any system because not two systems deal with them the same way and this problem is better solved in the individual packages.

If it no longer works on your system, you should try to mail your package maintainer so the package is fixed.
