### ISSUE TITLE
"SSL_CTX_use_certificate_chain_mem" is specific to LibreSSL

### ISSUE THREAD

**Issue by lhecker** [OpenSMTPD/OpenSMTPD#543]
As mentioned in https://github.com/OpenSMTPD/OpenSMTPD/issues/542#issuecomment-74420199:

OpenSMTPD currently cannot be built with OpenSSL, since `SSL_CTX_use_certificate_chain` got renamed to `SSL_CTX_use_certificate_chain_mem` in https://github.com/OpenSMTPD/OpenSMTPD/commit/381a37441f65bfbe980499d278d0013e4218a702, which is a function that only exists in LibreSSL.

I'm not sure if this is a bug worth being submitted here, or if this is working as intended. This might also be a problem with LibreSSL itself, since it would be beneficial for it to be as compatible as possible (e.g. a #define alias?).

**Comment by poolpOrg** [comment]
I have reproduced the problem on a Debian Linux.

Long story short, we relied on `SSL_CTX_use_certificate_chain` which was renamed to `SSL_CTX_use_certificate_chain_mem` in LibreSSL which is our dependency on OpenBSD.

To cope with this, a file named libressl.c was introduced a few days ago to provide the functions that are missing from OpenSSL. The file was not linked to the build however.

I have linked it and OpenSMTPD -portable now builds on Debian with OpenSSL.

This is a temporary fix but I'll close the ticket because the long run solution will be evaluated as part of ticket #534
