### ISSUE TITLE
Stale lock files

### ISSUE THREAD

**Issue by vext01** [OpenSMTPD/OpenSMTPD#549]
Hey,

My mail server crashed and I was forced to hard reboot it. When it came back up mail delivery was not working to my username due to a stale lock file `/var/log/edd.lock`. It was several days old before I noticed that mail was not being delivered.

Of course smtpd had been trying to mail me error reports, but since mail was not working, I did not receive them.

Once I removed the lock, a load of mail transferred from the mailq into my mbox.

I wonder if there is anything that can be done about stale lock files?

Thanks

**Comment by jirutka** [comment]
Lock file should be stored in `/run` that should be on tmpfs (in-memory filesystem), so it's implicitly cl

**Comment by poolpOrg** [comment]
This is not always doable because sometimes the lock has to be on an NFS share.

Anyways, the problem is not with OpenSMTPD which doesn't even know that a lock exists. The daemon passes the message to a mda without knowing what the mda will do with it besides acknowledging things went good or bad with the delivery.

On OpenBSD, the mbox mda is `mail.local` which is part of base system, it is not an OpenSMTPD component.

In portable, we ship mail.local as part of our contribs as most systems do not come with it, but it is by convenience to lift a possible dependency, not an OpenSMTPD component either.

There is nothing that can be done in OpenSMTPD to fix your stale lock issues, you need to fix your system's boot sequence to delete locks.

**Comment by vext01** [comment]
Hrm. FWIW this was an OpenBSD-5.6 machine.

**Comment by vext01** [comment]
So yes, looks like mail.local is the culprit for making the lock file.
