### ISSUE TITLE
realpath() on glibc with FORTIFY_SOURCE 

### ISSUE THREAD

**Issue by xtraeme** [OpenSMTPD/OpenSMTPD#551]
When opensmtpd is compiled with _FORTIFY_SOURCE on glibc, and using realpath(src, dest), dest must be at least 4096 bytes (PATH_MAX)... otherwise the glibc code will abort().

openbsd-compat/defines.h unsets PATH_MAX and redefines it as 1024...

I've removed this part simply because IMHO it makes no sense to undef PATH_MAX, and works as expected.

See this change as reference:

https://github.com/voidlinux/void-packages/commit/01523bbb48e0236385dfab00d138645904255284

**Comment by poolpOrg** [comment]
This was discussed a couple weeks ago on IRC, but the assessment and diff is okay.

Long story short, this hack by @clongeau was introduced because a long time ago we had structures which had 2/3 paths and on Linux systems with PATH_MAX set to 4k the structures exceeded the size of an imsg (16k) preventing atomic IPC writes.

Since then, we slowly got rid of the big structs and we modified our imsg patterns to rely on passing small messages so this hack is no longer needed. I'll double check that there's no more of these constructs *just to be sure* and kill the ifdef by the end of this week.

**Comment by xtraeme** [comment]
That explains why it was there, thanks.

**Comment by poolpOrg** [comment]
fix committed to tree, will be part of next snapshot / release, and we might just publish a patch level release for this
