### ISSUE TITLE
RFC: How to use opensmtpd-extras

### ISSUE THREAD

**Issue by lifeofguenter** [OpenSMTPD/OpenSMTPD#554]
It seems like v5.4.5 is almost out and it seems a lot has changed since the 5.4.4 version which should actually only be a minor version ;)

* how do we use the extra repository now? Should we just add the folder "extras" into the root src folder?
* how do we now compile mysql support? --with-experimental-mysql seems to be deprecated in favour of --with-table-mysql ?

**Comment by poolpOrg** [comment]
Actually you are mistaken, there is only minor changes between 5.4.4 and 5.4.5:

- a fix for a possible crash
- a fix for a minor yet annoying bug that happened after 5.4.4
- removed options that were no longer in opensmtpd but accidentally left in configure

The extras repository is a separate and standalone project, you need to clone it and configure/build it independently from OpenBSD, the only requirement is that they both share the same libexecdir so that extras are installed in the libexecdir where OpenSMPTD looks up for addons.

See instructions in the README.md from OpenSMTPD-extras which I just committed:

    https://github.com/OpenSMTPD/OpenSMTPD-extras/blob/master/README.md

Also keep in mind that we didn't release extras yet because there is still some work and polishing to do in that repository. The plan is to release it when we release our next major.
