### ISSUE TITLE
User can crash daemon by creating ~/.forward

### ISSUE THREAD

**Issue by TerrorBite** [OpenSMTPD/OpenSMTPD#583]
Version 5.4.1p1

By simply creating an apparently-valid `.forward` file in my home directory, I can cause the daemon to crash with no obvious error when an email addressed to my account is received (easily achieved by sending myself an email from an external service like gmail). This allows a non-root user to crash the daemon. Syslog:
```
Jun  5 12:23:12 localhost smtpd[28509]: smtp-in: New session ffffffffa06c0c00 from host mail-yh0-f54.google.com [209.85.213.54]
Jun  5 12:23:12 localhost smtpd[28509]: warn: smtp -> parent: pipe closed
Jun  5 12:23:12 localhost smtpd[28502]: warn: control -> parent: pipe closed
Jun  5 12:23:12 localhost smtpd[28501]: warn: queue -> parent: pipe closed
Jun  5 12:23:12 localhost smtpd[28507]: warn: scheduler -> control: pipe closed
Jun  5 12:23:12 localhost smtpd[28503]: warn: lka -> parent: pipe closed
Jun  5 12:23:12 localhost smtpd[28505]: warn: mfa -> parent: pipe closed
Jun  5 12:23:12 localhost smtpd[28504]: warn: mda -> parent: pipe closed
Jun  5 12:23:12 localhost smtpd[28506]: warn: mta -> parent: pipe closed
```

Regardless of whether I might have done something wrong setting up my `.forward`, such errors should not result in the daemon exiting, as this effectively allows a user to kill a privileged process.

Further details on request.

**Comment by TerrorBite** [comment]
Experimentation reveals that the daemon crashes the moment it receives the `RCPT TO:` command.

**Comment by poolpOrg** [comment]
What operating system? 
Can you provide configuration and content of forward file? 
Can you reproduce this with a more recent stable release? 5.4.1 is pretty old and various bugs have been fixed since then up to 5.4.5 
Le 5 juin 2015 9:46 PM, TerrorBite <notifications@github.com> a écrit :Experimentation reveals that the daemon crashes the moment it receives the RCPT TO: command.

**Comment by TerrorBite** [comment]
```
terrorbite@localhost:~$ uname -a
Linux localhost 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
terrorbite@localhost:~$ ls -l forward
-rw------- 1 terrorbite terrorbite 29 Jun  5 12:03 forward
terrorbite@localhost:~$ xxd forward
0000000: 7465 7272 6f72 6269 7465 406c 6574 6861  terrorbite@letha
0000010: 7267 6963 6c69 6f6e 2e6e 6574 0a         rgiclion.net.
terrorbite@localhost:~$ cat /etc/smtpd.conf
# This is the smtpd server system-wide configuration file.
# See smtpd.conf(5) for more information.

# To accept external mail, replace with: listen on all
listen on localhost
listen on eth0

# If you edit the file, you have to run "smtpctl update table aliases"
table aliases file:/etc/aliases

# If you edit the file, you have to run "smtpctl update table secrets"
table secrets file:/etc/secrets

# Uncomment the following to accept external mail for domain "example.org"
accept from any for domain "my-other.email" alias <aliases> deliver to mbox

#accept from local for local alias <aliases> relay via tls+auth://gmail@smtp.gmail.com:587 auth <secrets>
#accept for any relay

# Accept local outgoing mail and relay it through Gmail
accept from local for any relay via tls+auth://gmail@smtp.gmail.com:587 auth <secrets>
```

Note that the file is currently named "forward" instead of ".forward" since I wish to avoid triggering the crash for the time being. At this stage I have not tested with the latest version.

**Comment by poolpOrg** [comment]
No need to go further.

First of all, I'll point out _again_ that you are using a very old release from December 2013, we're currently 4 minor releases past yours, a year and a half later, and you haven't even tried the latest stable release to verify that your issue still exists before asking the developers to take on their own time to do that homework for you...

The issue you are hitting is caused by a compilation flag that Ubuntu passes to GCC by default and which causes the daemon to be aborted due to a buffer overflow. However, the buffer overflow is a false positive, the check is confused by some code of ours, it is possible to work-around it simply by building without that compilation flag.

Or I should really say "was".

If you had tried the latest stable release, you would not have experienced that crash.
