### ISSUE TITLE
makemap build and install issues

### ISSUE THREAD

**Issue by dfateyev** [OpenSMTPD/OpenSMTPD#584]
In the recent portable snapshot `"201506020910p1"` the `"makemap"` utility isn't built and installed, along with `"newaliases"` link and appropriate man-files for both. Although they were presented in the latest stable release.

**Comment by poolpOrg** [comment]
The latest stable, 5.4.5, is a minor release it only contains cumulative bug-fixes since 5.4.1 that was released a year and a half ago, whereas our snapshots are taken from the master branch which is very very current (commit 6 days ago), don't expect them to look alike ;-)

To answer your concern, the -db support has been a recurrent request for removal, people generally don't want it and don't want to depend on it. I had a bit of objection because it's such a historical feature, it just needs to be around, however with a new major release, we can keep it around as a configure option.

The --enable-table-db option will build table_db, makemap and create the newaliases link

**Comment by dfateyev** [comment]
OK, thanks. I missed that we need `"--enable-table-db"` for bdb4 from now on.

**Comment by poolpOrg** [comment]
On Mon, Jun 08, 2015 at 12:05:11PM -0700, Denis Fateyev wrote:
> OK, thanks. I missed that we need `"--enable-table-db"` for bdb4 from now on.
> 

This will be starting with next major release.

We're unfortunately going to have to publish a minor release very shortly
despite the major release being very close.

The minor release, 5.4.6, will be exactly like last stable release + fix,
so the db dependency is still part of it.


-- 
Gilles Chehade

https://www.poolp.org                                          @poolpOrg

**Comment by dfateyev** [comment]
Is the `"--enable-table-db"` switch no longer operational?
Quickly built with previously worked options set, and haven't got "makemap" again.

**Comment by poolpOrg** [comment]
It should still be operational but there's been a merge of `makemap` inside `smtpctl` and there's probably a packaging fix to do.

Ticket reopened, working on it

**Comment by f-andrey** [comment]
Ping

Any news?

**Comment by poolpOrg** [comment]
On Thu, Jan 14, 2016 at 09:16:45PM -0800, Andrey wrote:
> Ping
> 
> Any news?
> 

being worked on, it will be fixed before next snapshot

-- 
Gilles Chehade

https://www.poolp.org                                          @poolpOrg

**Comment by poolpOrg** [comment]
Hi,

Can you guys get back to me regarding this ?

We published a snapshot with the smtpctl / makemap merge.

Please note that we gave up on trying to handle mailwrapper vs non-mailwrapper systems so it is up to the individual systems to decide if they want makemap/mailq/newaliases utilities and to create the appropriate hardlink (symlink will do) to smtpctl.

Waiting for feedback to close ticket !

**Comment by dfateyev** [comment]
It's fine to me, just checked on the latest snapshot (201602031446p1).
Although got another issue, created #652.

**Comment by poolpOrg** [comment]
ok, the install being fine I'll close this ticket while we focus on the other one.
