### ISSUE TITLE
link to libasr in README

### ISSUE THREAD

**Issue by dfateyev** [OpenSMTPD/OpenSMTPD#585]
`README.md` mentions the `"libasr"` dependency like this:
> * [libasr] https://opensmtpd.org/archives/libasr-1.0.1.tar.gz

Better not to rely on a specific version since they are subject to change, but provide a link to `"libasr"` homepage (if exists) or its GitHub repo.

**Comment by poolpOrg** [comment]
I can't disclose too much because there are discussions in progress regarding the libasr dependency and the openbsd-compat glue.

All I can say at this point is that it is unlikely libasr will ever have a page of its own and that we're heading towards merging it with the openbsd-compat glue as suggested by eric.

When this happens, shortly after our next major release this month, the mention to libasr in the README will simply go away.

For now I bumped it to 1.0.2 so there's a direct link to the tarball
