### ISSUE TITLE
pki and auth for wildcard certificates

### ISSUE THREAD

**Issue by tub5ta** [OpenSMTPD/OpenSMTPD#598]
Can the feature for wildcard certificates be added so wildcard certificates can be used in pki and auth instances.  For example:

pki *.mail.example.com certificate "/etc/ssl/wildcard.mail.example.com.crt"
pki *.mail.example.com key "/etc/ssl/private/wildcard.mail.example.com.key"

listen on lo0
listen on egress tls pki *.mail.example.com
listen on egress port 587 tls pki *.mail.example.com auth

Thanks!

**Comment by poolpOrg** [comment]
Better late than never:

I'm currently working on switching OpenSMTPD from libssl to libtls and a side-effect is that how we deal with certificate lookups gets simplified: we no longer lookup for certificates by PKI name but register valid certificates for a listener and let libtls to the proper matching, including wildcards.

As a result, your feature request will be closed because it will not be implemented as is and your use-case will be magically solved when development of branch libtls gets merged in master.
