### ISSUE TITLE
failed precmd routine for smtpd

### ISSUE THREAD

**Issue by xmj** [OpenSMTPD/OpenSMTPD#617]
Hi there,

I'm installing opensmtpd-devel (from FreeBSD ports, version opensmtpd-devel-201506112227) on a FreeBSD 10.1-RELEASE box within a jail created by iocage.

I'm seeing the following error:

failed: [perceivon02] => {"changed": true, "cmd": "iocage exec dd8af675-2953-11e5-ad68-a710c4a2a00f /bin/sh -c \"service smtpd start\"", "delta": "0:00:01.546799", "end": "2015-07-13 07:11:52.511335", "rc": 1, "start": "2015-07-13 07:11:50.964536", "warnings": []}
stderr: invalid hostname: getaddrinfo() failed: hostname nor servname provided, or not known
/usr/local/etc/rc.d/smtpd: WARNING: failed precmd routine for smtpd
stdout: Performing sanity check on smtpd configuration:

FATAL: all hosts have already failed -- aborting

What's necessary to fix it, beyond putting a hostname in /etc/hosts ?

**Comment by poolpOrg** [comment]
We don't take care of packaging for different systems, I'll have a look at this to determine if it is a problem with our code or with the packaging on your system.

I'll get back to you by this week-end

**Comment by poolpOrg** [comment]
Sorry for the delay, got swamped all of a sudden.

I don't think there is a problem with OpenSMTPD, it expects a hostname to exist on the machine where it runs and in your cases it simply doesn't.

This can either be fixed by adding a hostname in /etc/hosts, or creating a mailname file in the appropriate directory (usually /etc/mail, /etc, /usr/local/etc, ... depends on what your package maintainer decided was a good choice).

There is really nothing to fix here as far as I know, I'll close the ticket.
