### ISSUE TITLE
Recipients without domain part not accepted

### ISSUE THREAD

**Issue by osalmi** [OpenSMTPD/OpenSMTPD#620]
Hi,

After upgrading to 5.7.1, recipient address without a domain, e.g. `RCPT TO: <postmaster>`, is rejected with `550 Invalid recipient`:
```
smtp: 0x16ecb58b9000: <<< RCPT TO: <postmaster>
filter: new query QK_QUERY QUERY_RCPT
filter: filter_drain_query c6834f2b9311785b[QK_QUERY,QUERY_RCPT=postmaster@,filter_session@0x16ece8af5e00[datalen=0,eom=0x0,ofile=0x0]]
filter: filter_end_query c6834f2b9311785b[QK_QUERY,QUERY_RCPT=postmaster@,filter_session@0x16ece8af5e00[datalen=0,eom=0x0,ofile=0x0]]
filter: query c6834f2b9311785b done: status=FILTER_OK code=0 response="(null)"
mproc: pony -> lka: realloc 128 -> 256
mproc: pony -> lka : 248 IMSG_SMTP_EXPAND_RCPT
imsg: lka <- pony: IMSG_SMTP_EXPAND_RCPT (len=248)
expand: 0x16ecab5d9018: expand_insert() called for address:postmaster@[parent=0x0]
expand: 0x16ecab5d9018: inserted node 0x16ecb3fc6000
expand: lka_expand: address: postmaster@ [depth=0]
lookup: check "127.0.0.1" as NETADDR in table static:<localhost> -> found
lookup: check "" as DOMAIN in table static:<localnames> -> 0
lookup: check "127.0.0.1" as NETADDR in table static:<localhost> -> found
lookup: check "" as DOMAIN in table static:<anydestination> -> 0
no rule matched
mproc: lka -> pony : 37 IMSG_SMTP_EXPAND_RCPT
expand: 0x16ecab5d9018: clearing expand tree
imsg: pony <- lka: IMSG_SMTP_EXPAND_RCPT (len=37)
smtp: 0x16ecb58b9000: >>> 550 Invalid recipient
smtp-in: session c6834f260d50b0d6: received invalid command: "RCPT TO: <postmaster>"
```

Tested on OpenBSD 5.7 using the default configuration:
```
listen on lo0

table aliases db:/etc/mail/aliases.db

accept for local alias <aliases> deliver to mbox
accept from local for any relay
```

Ossi

**Comment by poolpOrg** [comment]
verified, I'll issue a fix shortly

**Comment by poolpOrg** [comment]
These were my famous last words before I got trapped in real life.

I'm tracking the regression and will have something for you to test this week-end.

**Comment by poolpOrg** [comment]
Nevermind the diff, I have spotted the issue and fixed the regression.

When we reworked valid_domainpart() to use res_hnok() rather than self-rolled logic, we missed the fact that it considers empty strings as valid hostnames... which causes our fallback code for empty domains to be bypassed.

The fix is already committed to OpenBSD -current if you're using the smtpd from base, and github if you're using the smtpd from there. We'll publish a minor version with this fix applied shortly, we want to tackle a few others bugs as well.

Thanks for your report
