### ISSUE TITLE
Add case (in)sensitivity option to table

### ISSUE THREAD

**Issue by satan1st** [OpenSMTPD/OpenSMTPD#626]
Hi

It would be nice if you could add an option to define if the key lookup for a table should be case-sensitive or not.

**Comment by MercSec** [comment]
Related to RFC 821 his request is no feature request.

--
Commands and replies are not case sensitive.  That is, a command or
 reply word may be upper case, lower case, or any mixture of upper and
 lower case.  Note that this is not true of mailbox user names.  For
 some hosts the user name is case sensitive, and SMTP implementations
 must take case to preserve the case of user names as they appear in
 mailbox arguments.  Host names are not case sensitive.
--

**Comment by poolpOrg** [comment]
Hi,

Could you please explain the use-case for this, we're currently discussing with @ericfaurot and can't seem to find a use-case where case-sensitivity is an issue in lookups.

Gilles

**Comment by satan1st** [comment]
Hi

I have two usecases

First I would like to seperate mails for john@example.com and John@example.com.

Secound I write on a Graylisting-filter, which need to have a case-sensitive lookup. I want to use the table interface as data store.

A third usecase would be, to move an old case-sensitive setup to OpenSMTPD.

Philipp

**Comment by poolpOrg** [comment]
I don't think we will ever support that:

For the first use-case, we have decided years ago that OpenSMTPD would be case-insensitive and that it would case-fold to lowercase all addresses + usernames. This is a design decision that works for most users and that allows us to keep simple and clean all code paths that deal with usernames and addresses.

Adding support for case-sensitive addresses implies far more than adding case-sensitive keys to tables. It implies making aliases expansion, virtual expansion, system-user lookups, delivery and possibly other layers that I can't think of right now case-aware.

Assuming that we had a way to decide that some lookups are sensitive and others don't, which is already an issue of its own, we could end up with ambiguous lookups because some layers perform cross-table lookups and may start a case-sensitive lookup that has an internal case-insensitive lookup.

The effort required for this feature and the "benefit" we obtain from it is not worth the effort in our opinion.


Regarding your second use-case, tables are not meant to be queried (directly) by filters, this is an API that's exclusively intended for daemon-side use. Filters may only access data that the daemon hands them over, provides them through the filter API or that the filters manage themselves. Tables can already handle some sensitive data and may handle more in the future, we don't want buggy filters to expose that data by accident.


For the third use-case, I don't think we'll have a solution for you, we don't want to kludge the code with weird cases so old setups can be moved.

If you came up with a non-invasive diff that didn't come with side-effects, I would not necessarily be opposed, but I doubt you can achieve that really.

Closing the ticket as won't fix, feel free to submit a pull request if you manage the above
