### ISSUE TITLE
DMARC + DKIM

### ISSUE THREAD

**Issue by reyk** [OpenSMTPD/OpenSMTPD#643]
I know that smtpd.conf(5) mentions DKIM. I think it is rather horrible to pipe all my mail through a Perl-based proxy. Is there any other way to support this stuff directly? Maybe a privsep'd process in smtpd?

DMARC, which includes DKIM, is also concerning me, as it soon becomes mandatory, at least on the sender side to submit email to Gmail and all the other big ones: https://dmarc.org/2015/10/global-mailbox-providers-deploying-dmarc-to-protect-users/

It would be nice to have all this stack documented and ready with OpenSMTPD. The industry seems to push everyone to stop running "private" mail servers. Of course, this is all done to fight spam, but with the convenient side-effect of further decentralizing Internet email.

**Comment by poolpOrg** [comment]
On Wed, Oct 21, 2015 at 11:56:03PM -0700, Reyk Floeter wrote:
> I know that smtpd.conf(5) mentions DKIM. I think it is rather horrible to pipe all my mail through a Perl-based proxy. Is there any other way to support this stuff directly? Maybe a privsep'd process in smtpd?
> 
> DMARC, which includes DKIM, is also concerning me, as it soon becomes mandatory, at least on the sender side to submit email to Gmail and all the other big ones: https://dmarc.org/2015/10/global-mailbox-providers-deploying-dmarc-to-protect-users/
> 
> It would be nice to have all this stack documented and ready with OpenSMTPD. The industry seems to push everyone to stop running "private" mail servers. Of course, this is all done to fight spam, but with the convenient side-effect of further decentralizing Internet email. 
> 

The example described in smtpd.conf(5) assumes that filters do not exist
and provides a solution for that case.

There's a dkim filter which allows you to have dkim in a privsep process
without resorting to a proxy.

-- 
Gilles Chehade

https://www.poolp.org                                          @poolpOrg

**Comment by denji** [comment]
libdkim++ is a lightweight and portable DKIM (RFC4871) library for *NIX, supporting both signing and DMARC/SDID/ADSP verification
* https://github.com/halonsecurity/libdkimpp

**Comment by poolpOrg** [comment]
@reyk are you opposed to running rspamd ?

**Comment by crepererum** [comment]
Some additional info from my own setup:

I was using the DKIM filter that was in the extra repo, but was removed due to restructuring. For people trying to use an old version of OpenSMPTD, which should be compatible with the old filter code, here is a warning: despite of the maybe occurring file descriptor leaks within the old filter code, there is another bug: the filter produces wrong signatures for mails with multiple recipients (i.e. multiple entries within the `to` header).

I'm currently running the following, perfectly working, setup:
- sign all outgoing emails with dkimproxy, using a loopback design `OpenSMTPD -> dkimproxy -> OpenSMPTD` (using flags), since I trust OpenSMTPD to do the right thing when communicating with the outer world, but I'm kinda worried about dkimproxy
- check incoming mails using rspamd, called by dovecot (so not as part of the SMTP pipeline), "only" increasing the spam score when facing invalid signatures

**Comment by denji** [comment]
@crepererum https://github.com/OpenSMTPD/OpenSMTPD-extras/tree/filter-rspamd/extras/filters/filter-rspamd
* https://github.com/vstakhov/rspamd#spam-filtering-features

**Comment by poolpOrg** [comment]
There is ongoing work in https://github.com/OpenSMTPD/OpenSMTPD/projects/1 and ticket #773 , closing this ticket as is is referenced in the other which is already assigned.
