### ISSUE TITLE
Feature request: ability to have prefix aliases like: my-prefix-*@mydomain.com

### ISSUE THREAD

**Issue by obadz** [OpenSMTPD/OpenSMTPD#685]
It would be great if we could define aliases of this type:

```
my-prefix-*@mydomain.com => me@mydomain.com
```

As long as the wildcard `*` is at the end of the username (and it would be acceptable to disallow other types of entry) this should be computationally inexpensive as this data structure is represented as a tree. (Already the case from glancing at the source code I believe).

**Comment by poolpOrg** [comment]
We have discussed this a bit at the p2k16 hackathon and while we're not opposed to the idea, it isn't as simple as you assume because:

> As long as the wildcard * is at the end of the username (and it would be acceptable to disallow other types of entry) this should be computationally inexpensive as this data structure is represented as a tree. (Already the case from glancing at the source code I believe).

This is not true at all, there are several lookup backends, some being unable to cope with this, others being able to cope naturally and others requiring additional work to be able to cope.

We're not closing the ticket and dismissing the idea, just making it clear that it will not happen very soon because it needs some thinking to do it the right way.

**Comment by poolpOrg** [comment]
@ericfaurot and I have discussed this again and there is no way this can be done in a clean way within smtpd, this can certainly be done with a smtpfd filter when we're finished with #773
