### ISSUE TITLE
filters: track descriptor leak

### ISSUE THREAD

**Issue by poolpOrg** [OpenSMTPD/OpenSMTPD#698]
There is a descriptor leak somewhere in the filter code path which causes some setups to crash after a while.

It doesn't happen in all code paths, I can create a setup similar to those who experience crashes and have it survive a blast of concurrent sessions.

It doesn't happen to everyone and while it seems to trigger relatively fast to some, others tell me that they can run for weeks if not months without experiencing a leak. @ericfaurot couldn't reproduce and I couldn't reproduce even.

This issue is seen in tickets: #619 and #674 

Since these tickets are actually two symptoms of the same issue, that they also had other issues which we fixed in between and because they grew too large & confusing for us to grasp what is still an issue or not, I'm closing them and opening this new on to track the problem.

There is also a possibility that the issue was caused by a leak that was fixed before the 5.9.2 release, so currently waiting for feedback from various users.

Issue handled by @poolpOrg and @ericfaurot 

Waiting for feedback from:
- @hrkfdn
- @crepererum
- @jdelic
- @bdijkstra82

Make sure to let us know:
- which version of OpenSMTPD you are using
- which filter(s) you are using and their version
- which process has the leak
- as much log as you can provide

The more information we receive, the sooner we squash this.

**Please also note that a leak in the filter code path was plugged just before the 5.9.2 release, make sure that you're running with latest version**

**Comment by crepererum** [comment]
I'm currently running only the DKIM filter from [the master branch](https://github.com/OpenSMTPD/OpenSMTPD-extras/commit/46e373e9e12a06b81053244a2a3bfa5d863023d4) in combination with OpenSMTPD 5.7.3 since #694 prevents me from upgrading. That seems to work perfectly (for now). I only have a very low amount of mails passing through that filter so it's unlikely that I'll see the long term issue soon. Also systemd is restarting the server in case of a crash.

**Comment by hrkfdn** [comment]
I've moved from filter-spamassassin to filter-dnsbl which has solved my problems for now. Quite busy now, but I will setup a spamassassin filter again soon to test this.

**Comment by bdijkstra82** [comment]
Does it still make sense to report about descriptor leaks that occur due to sleep() and/or other synchronous delays?

**Comment by poolpOrg** [comment]
On Fri, Jun 03, 2016 at 05:45:14AM -0700, bdijkstra82 wrote:
> Does it still make sense to report about descriptor leaks that occur due to sleep() and/or other synchronous delays?
> 

yes, the daemon not working correctly when a filter is not designed
correctly is not so much a real issue, a leak however should not
happen as it indicates that an error code path doesn't cleanup its
state correctly.

-- 
Gilles Chehade

https://www.poolp.org                                          @poolpOrg

**Comment by poolpOrg** [comment]
I have managed to reproduce reliably, this bug is living its last hours

**Comment by poolpOrg** [comment]
Eric managed to reproduce and apparently has a fix, we'll get back to you shortly.

**Comment by poolpOrg** [comment]
so, eric has committed what seems to be the fix to this long standing issue.

it is located in the -extras api layer, so you can simply rebuild your filters with code from git, or use upcoming extras snapshots/release.

we found a similar code construct in smtpd but it cannot be triggered as far as we know and certainly not when filters are enabled, we still fixed it just to be sure.

please test and report that you no longer experience issues now ! :-)

**Comment by bdijkstra82** [comment]
Running OpenSMTPD 5.9.1 on OpenBSD 5.9 with patch 006 and -extras from yesterday, with a filter that sleeps on every event except on_dataline and then rejects on_eom. Still getting a significant amount of descriptor leaks.

E.g.:
> debug: smtp: 0x7df81000: data io done (1928 bytes)
> filter: new query QUERY_EOM
> filter: filter_drain_query 51fe09fe42114b45[QUERY_EOM,filter_session@0x8076b900[datalen=1546,eom=0x0,ofile=0x26a42200]]
> filter: running filter filter:spamd[hooks=0xffffffff,flags=0x0000] for query 51fe09fe42114b45[QUERY_EOM,filter_session@0x8076b900[datalen=1546,eom=0x0,ofile=0x26a42200]]
> filter: waiting for running query 51fe09fe42114b45[QUERY_EOM,filter_session@0x8076b900[datalen=1546,eom=0x0,ofile=0x26a42200]]
> filter: filter_tx_io(0x8076b900, IO_DATAIN)
> filter: filter_tx_io: datain (380) for req 51fe09f8a06c4fa7

Session halts here, but I would expect:
> spamd[30773]: debug: 51fe09ff8b2bdd92 on_eom
> ...
> spamd[30773]: debug: 51fe09ff8b2bdd92 on_disconnect

**Comment by poolpOrg** [comment]
When in this state, can you still connect to smtpd and get a banner? 
If it's the case, it isn't a leak but rather a problem with the filter itself, which is much better than the previous issue for us as it will not apply to all filters 
Le 8 juin 2016 11:37 AM, bdijkstra82 <notifications@github.com> a écrit :Running OpenSMTPD 5.9.1 on OpenBSD 5.9 with patch 006 and -extras from yesterday, with a filter that sleeps on every event except on_dataline and then rejects on_eom. Still getting a significant amount of descriptor leaks.

E.g.:


debug: smtp: 0x7df81000: data io done (1928 bytes)
filter: new query QUERY_EOM
filter: filter_drain_query 51fe09fe42114b45[QUERY_EOM,filter_session@0x8076b900[datalen=1546,eom=0x0,ofile=0x26a42200]]
filter: running filter filter:spamd[hooks=0xffffffff,flags=0x0000] for query 51fe09fe42114b45[QUERY_EOM,filter_session@0x8076b900[datalen=1546,eom=0x0,ofile=0x26a42200]]
filter: waiting for running query 51fe09fe42114b45[QUERY_EOM,filter_session@0x8076b900[datalen=1546,eom=0x0,ofile=0x26a42200]]
filter: filter_tx_io(0x8076b900, IO_DATAIN)
filter: filter_tx_io: datain (380) for req 51fe09f8a06c4fa7


Session halts here, but I would expect:


spamd[30773]: debug: 51fe09ff8b2bdd92 on_eom
...
spamd[30773]: debug: 51fe09ff8b2bdd92 on_disconnect

**Comment by bdijkstra82** [comment]
When in this state, I can indeed connect to smtpd. An on_connect event is triggered immediately, a banner appears and commands seem to get processed as normal.

**Comment by poolpOrg** [comment]
On Thu, Jun 09, 2016 at 01:15:25AM -0700, bdijkstra82 wrote:
> When in this state, I can indeed connect to smtpd. An on_connect event is triggered immediately, a banner appears and commands seem to get processed as normal.
> 

Is the leak happening in the filter or the daemon ?


-- 
Gilles Chehade

https://www.poolp.org                                          @poolpOrg

**Comment by bdijkstra82** [comment]
How can I tell? Both processes have more sockets than they should have...

**Comment by poolpOrg** [comment]
Well, you can tell by providing the following:

- ps auxwww | grep _smtpd
- smtpctl show stats
- fstat -u _smtpd

This will let us know the PID of the different processes (assuming your filters run as _smtpd), the number of active sessions according to the daemon and the number of descriptors used by the different _smtpd processes, including filters (assuming they run as _smtpd still).

**Comment by bdijkstra82** [comment]
Here is the output of ps with the user omitted and the number of open files prepended:
```
 11   6680  0.0  0.8  1428  2052 p2  I+p   Mon09AM    0:00.63 smtpd: lookup (smtpd)
 14    441  0.0  0.8  1484  1996 p2  I+p   Mon09AM    0:00.19 smtpd: control (smtpd)
 10  28178  0.0  0.7  1280  1748 p2  I+p   Mon09AM    0:00.01 smtpd: klondike (smtpd)
  9   1739  0.0  0.7  1216  1804 p2  I+p   Mon09AM    0:00.32 smtpd: scheduler (smtpd)
139  26669  0.0  2.2  7608  5636 p2  I+p   Mon09AM    0:08.63 smtpd: pony express (smtpd)
 47  18599  0.0  0.6  3364  1636 p2  I+    Mon09AM    0:02.29 spamd -v -d (filter-spamd)
```
And here is smtpctl show stats:
```
control.session=1
queue.evpcache.size=44
scheduler.envelope.incoming=44
scheduler.ramqueue.envelope=44
scheduler.ramqueue.message=44
scheduler.ramqueue.update=44
smtp.session=44
smtp.session.inet4=393
uptime=186852
uptime.human=2d3h54m12s
```

**Comment by poolpOrg** [comment]
GREAT !

This output is going to be really useful, thank you

**Comment by poolpOrg** [comment]
Snapshots for both OpenSMTPD and -extras have been published.

The OpenSMTPD snapshot fixes a case of leak and invalid session state that happens when a filter is rejecting a hook.

The -extras snapshot converts filter-spamassassin and filter-clamav to being non-blocking, the fact they were making blocking calls was overlooked.

Please test these two snapshots together and let us know if things get better.

**Comment by poolpOrg** [comment]
any news ?

**Comment by bdijkstra82** [comment]
Is the OpenSMTPD snapshot in sync with OpenBSD's CVS?

I tried to find the mentioned filter conversion diffs, but couldn't find them in the github history. Should it show up e.g. [here](https://github.com/OpenSMTPD/OpenSMTPD-extras/commits/master/extras/filters/filter-clamav/filter_clamav.c)?

**Comment by poolpOrg** [comment]
As mentioned in the mailing-list, we have found a design issue in how filters are implemented and are going to be refactoring the code in a much different way.

I'll close this ticket until we reintroduce the new design as it makes no sense tracking the leak in code that is going away.

**Comment by jdelic** [comment]
> As mentioned in the mailing-list, we have found a design issue in how filters are implemented and are going to be refactoring the code in a much different way.

Just in general, I am personally convinced that giving as much *context* as possible is important for a ticket tracking system to be useful to the community or even just attached developers.

Unfortunately I can't find anything about what design issues have been identified, or any pubic discussion about what steps are going to be taken to resolve them. But to provide as much context to this ticket as I can for everybody who is monitoring this: the best explanation for what happened with filters that I found is [this email by @poolpOrg](https://www.mail-archive.com/misc@opensmtpd.org/msg03171.html) on the OpenSMTPD mailing list.

@bdijkstra82 
> I tried to find the mentioned filter conversion diffs, but couldn't find them in the github history. Should it show up e.g. here?

I read through the code changes in OpenSMTPD-extras from FILTER_API version 50 (5.7 - 5.9) to 51 (6.0) and then 52 (master/portable) and I am unable to figure out what the direction of the current refactor is either. There seems to be no document, ticket or discussion out there that explains it. Obviously, as is always the case with OpenBSD, the use of CVS as the actual main SCM system is... "unhelpful". What I can definitely say though is that no (checked-in/publicly available) filter code has been updated to API version 52, which is why the one filter that I can't do without on Debian, [my own opensmtpd-filter-greylistd](https://github.com/jdelic/opensmtpd-filter-greylistd), is currently compiled against an unreleased version of OpenSMTPD-extras on version 51.

**Comment by poolpOrg** [comment]
The reason why I'm not providing context is precisely because I'm no longer willing to cope with everyone trying to play and workaround the fact that the feature is not ready and releasing unstable code that people send us bug reports about.

I honestly think that we could have moved forward 2x/3x times faster if we didn't have to cope with people releasing half-baked filters that generated LOTS of mails about bugs that were either not in our code but still required us to investigate and/or code that wasn't meant to be used yet because *we were not done yet ...*

The fact that you already "can't do without" a filter despite the fact the API was not finalized is a good indicator that I'm taking the correct approach this time, and we'll release the new refactored code when we are in a place where we can actually cope with this.

I know it sucks, I know people want the feature, but I'm not willing to write crap just to serve it right away and not willing to take an insane amount of pressure because other people are writing crap just to serve it right away because I don't do it ;-)

PS: don't take it personnally, I'm not targeting anyone, just stating the last 9 months or so where I received daily mails about issues that I knew existed or that I didn't know were released in the wild as if filters were stable.
Gilles

**Comment by jdelic** [comment]
> The reason why I'm not providing context is precisely because I'm no longer willing to cope with everyone trying to play and workaround the fact that the feature is not ready and releasing unstable code that people send us bug reports about.

Hmm, that's not the kind of context I meant. I was simply referring to you mentioning a mailing list post without linking it and a design deficiency without naming it. That makes the issue opaque and doesn't help people make informed decisions and I was only able to provide one of the two. Let me try and clear this up:

>The fact that you already "can't do without" a filter despite the fact the API was not finalized is a good indicator that I'm taking the correct approach this time, and we'll release the new refactored code when we are in a place where we can actually cope with this.

I should have been more clear that *I am* writing the mentioned filter myself to solve *my* problems (in this case a lack of `spamd` on Linux) and I am perfectly aware of what the the filter API's abysmal state is and that it will probably burn my house down. I think many people on this repo are aware of that. In my case, the alternative would be postfix and I am not doing *that* or going back to qmail and I am not doing *that either*. So yeah, I run OpenSMTPD with my own code to get a sane email setup. It'll be fine 😀. (At the very least it won't be your house). I know all that, because I read the code, many tickets on this GitHub, participated in maintaining the (broken) Debian packages and run OpenSMTPD and played around with the old filter API.

> I know it sucks, I know people want the feature, but I'm not willing to write crap just to serve it right away and not willing to take an insane amount of pressure because other people are writing crap just to serve it right away because I don't do it ;-)

And that's just it. The feature deserves to be done right, by the core developers. But it would be nice to have some kind of visibility into what was wrong with the old filter API so mistakes can be avoided in the future and it seems that knowledge between you and Eric currently has a bus factor of 2. It's clear that nobody else knows OpenSMTPD's internals well enough to figure out the core design deficiency that you guys found without sufficient hand-holding, otherwise there would be a healthy discussion going on about how to fix it. So that's the context I'm talking about... we're on GitHub and not a user forum. If I can't figure out where this is going after all the time I spent with OpenSMTPD, that's an unfortunate state of affairs, since it means that core issues of this open-source project aren't "open-sourced". I hope you understand that this is also not meant as personal criticism, I think there are larger issues at play around how the project is structured with OpenBSD's infrastructure and obviously about how the filter API played out previously.

In any case, I do hope that the refactoring goes quickly though, as I'm looking forward to using a stable non-house-burning API :). I will also do my best to not write crap... that's usually my policy when writing code (with a special exception for PHP :p). The world deserves a modern, sane, fast, secure email server with a healthy community.

Anyway, sorry for again spamming a closed ticket.
