### ISSUE TITLE
PAM configuration

### ISSUE THREAD

**Issue by Yamakaky** [OpenSMTPD/OpenSMTPD#712]
Apparently opensmtpd supports PAM, but I can't find any mention of it in the doc. How can I use this feature?

**Comment by poolpOrg** [comment]
This is a question for the mailing-list or IRC channel.

Quick reply:

You need to configure --with-auth-pam and provide the auth service name as parameter then configure the PAM side on your system.

I'll close this as it's not a bug, please use proper media and reopen ticket if it turns out you are facing a PAM-related bug.

**Comment by Yamakaky** [comment]
Shouldn't it be on the README?

**Comment by poolpOrg** [comment]
why not, feel free to send a pull request and I'll merge
