### ISSUE TITLE
Allow negation of the "authenticated" property

### ISSUE THREAD

**Issue by assistcontrol** [OpenSMTPD/OpenSMTPD#744]
Can the accept/reject grammar be extended to allow negation of the `authenticated` property?

I'd want to use it for rejecting forged messages claiming to be from me, but to skip the test if I submitted it over an authenticated session.

```
reject ! authenticated from ! source <other-relays> sender "@example.com" for any
```

I realize that I can tag unauthenticated messages and then test the tagged messages, but `! authenticated` is more precise and is the correct English description of what I'm trying to accomplish.

**Comment by poolpOrg** [comment]
On Fri, Nov 25, 2016 at 11:14:57AM -0800, Adam Weinberger wrote:
> Can the accept/reject grammar be extended to allow negation of the `authenticated` property?
> 
> I'd want to use it for rejecting forged messages claiming to be from me, but to skip the test if I submitted it over an authenticated session.
> 
> ```
> reject ! authenticated from ! source <other-relays> sender "@example.com" for any
> ```
> 
> I realize that I can tag unauthenticated messages and then test the tagged messages, but `! authenticated` is more precise and is the correct English description of what I'm trying to accomplish.
> 

What a timing...

I have a diff doing some parse.y improvement and I realized we lacked
the negation of authenticated so I implemented it just an hour ago :)

Please give me a week, if I'm done with the parse.y change I'll push
the feature as part of it, otherwise I'll do a backport to current
code.


-- 
Gilles Chehade

https://www.poolp.org                                          @poolpOrg

**Comment by assistcontrol** [comment]
Good stuff. Thanks, Gilles.

**Comment by poolpOrg** [comment]
diff waiting for ok's to be commited, probably today

**Comment by poolpOrg** [comment]
committed, this will be in next snapshots and next major release
