### ISSUE TITLE
missing sendmail compat flags

### ISSUE THREAD

**Issue by ajacoutot** [OpenSMTPD/OpenSMTPD#761]
Hi.

The Alpine MUA uses the following sendmail(8) flags by default:
-bs -odb -oem
Some aren't supported by OpenSMTPD which makes it impossible to send mail.

This was reported on misc@opensmtpd.org by Damian McGuckin:
Subject: using '[al]pine' with OpenSMTP

**Comment by snimmagadda** [comment]
Hi,

I posted a diff on the mailing list to fix this issue. Comments, test reports welcome.

**Comment by poolpOrg** [comment]
discussed with @snimmagadda a while ago and @ericfaurot a few minutes ago, this is a MUA config change that's not worth the kludge we'd add to smtpctl to fake sendmail options parsing.

**Comment by edrozenberg** [comment]
I also had this issue and found a workaround, by configuring Alpine/mutt to use ```mail -t``` as the "sendmail program" for outbound email. 

I documented the mutt and alpine configuration steps I followed a few comments down the page at https://github.com/OpenSMTPD/OpenSMTPD/issues/840

Note that when using the ```mail``` binary with opensmtpd **not running**, mail will return an "OK sent" essentially, even though the mail is actually queued in ```/var/spool/smtpd/offline```.

This is exactly what I want personally, but some people prefer the behavior where if opensmtpd is down/offline, the attempt to send mail should return an error code. For that case, use ```sendmail -t``` instead of ```mail -t``` in the mutt and alpine configurations. ```sendmail -t``` returns error code 75 when message is added to offline and smtpd is not running.
