### ISSUE TITLE
mbox keeps getting trunicated to 0 length

### ISSUE THREAD

**Issue by pouar** [OpenSMTPD/OpenSMTPD#778]
Not sure if it is related, but I think someone is trying to bruteforce their way into my server, not sure if it has anything to do with it or not, but it's the only thing I can find in the logs. I'm currently using Maildir as a work around. Does OpenSMTPD append to the end of an mbox file or rewrite the whole thing?
[smtpd.conf](https://github.com/OpenSMTPD/OpenSMTPD/files/894793/smtpd.conf.txt)
[syslog](https://github.com/OpenSMTPD/OpenSMTPD/files/894794/syslog.txt)

**Comment by poolpOrg** [comment]
Please next time ask questions like this in the mailing-list, there are more people reading them who can answer and it doesn't trigger a notification to developers ;-)

OpenSMTPD does not rewrite the file, this would be very inefficient.

Instead it relies on mail.local which is a utility that has been imported in OpenBSD 21 years ago and been in use with both Sendmail and OpenSMTPD since then without anyone complaining about truncated mbox.

If there's a problem with mbox truncation it's in the mail.local utility (which I doubt), are you sure your MUA isn't culprit here ?

**Comment by pouar** [comment]
*facepalms* I'm an idiot. My MUA is setup to import them automatically.

**Comment by poolpOrg** [comment]
there you go ;-)

closing the ticket.
