### ISSUE TITLE
Bug: Smtpd hangs without output

### ISSUE THREAD

**Issue by mikygee** [OpenSMTPD/OpenSMTPD#811]
Smtpd hangs and doesn't produce output error message when misconfigured
Version: 6.0.0

* smtpd.conf
table aliases file:/etc/mail/aliases
listen on lo0
accept for local alias <aliases> deliver to mbox
accept from local for any relay via smtp://10.1.1.1

* The resolv.conf file should be also faulty and point to a non existant DNS
nameserver 3.3.3.3

The entry shouldn't correspond to your machine
# cat /etc/hosts
1.1.1.1 faulty.mydomain.org faulty

# smtpd -vd
<hangs>

If I correct myserver.mydomain.org or myserver in /etc/resolv.conf it works
# smtpd -vd
debug: init ssl-tree
....

I don't know why smtpd reads these files but at least it should exit with an error status, not crash.

Regards

**Comment by poolpOrg** [comment]
Investigated and this is not a bug.

SMTP relies on a working DNS and it is expected that a broken DNS setup will result in a broken SMTP setup: DNS is used for both incoming and outgoing trafic.

Your analysis in the last paragraph is incorrect:

First of all, OpenSMTPD didn't read these files, it relies on the DNS resolver which does.

Then, it should most definitely not exit because DNS errors are transient, the files could be fixed and the resolver could re-read them.

Finally, the daemon isn't hanged and most definitely not crashed, it _appears_ to be hanged because the individual sessions are blocked waiting for DNS to be fixed. I replicated a setup with a broken resolv.conf and sessions connecting to the daemon seemed hanged, however connecting to the loopback interface or through the local enqueuer worked perfectly, if there were pending deliveries to local users they would work perfectly too.

In your example, you have completely broken DNS on the system by breaking both resolv.conf and /etc/hosts, so obviously nothing relying on a DNS lookup will work, but exiting the daemon with an error message would be the worst thing to do.

The fix is to not break your DNS on a system relying on DNS :-)
