### ISSUE TITLE
extras: table-ldap - bind with user credentials given during smtp auth

### ISSUE THREAD

**Issue by pvagner** [OpenSMTPD/OpenSMTPD#812]
I am trying to setup opensmtpd + dovecot + openldap email system on arch linux.
This blog article from 2015 is the only usefull source of info I was able to gather on this topic. I mean this one: https://www.tumfatig.net/20150718/opensmtpd-dovecot-and-ldapd-on-openbsd-5-7/
After experimenting a bit with similar config featured in the article and finally finding this unanswered post from september 2016: https://www.mail-archive.com/misc@opensmtpd.org/msg03168.html
I have came to some assumptions:
* OpenSMTPd binds to ldap by using the credentials from the config file e.g. /etc/mail/ldap.conf . It newer hands smtp credentials to ldap server. It retrieves credentials according to the credentials_filter and credentials_attributes configuration options.
* So by knowing OpenSMTPd does not bind to ldap with user provided credentials I think we have to configure the same password hashing scheme for opensmtpd and openldap. This is kinda unfortunate as this is something ldap is supposed to address and we should not have to wory about password schemes, hashing and similar stuff.
* So at one hand we do have OpenSMTPd with its built-in non-configurable crypt 3 password hashing (on my system these are SHA512 hashes, the crypt implementation and configuration may differ I think) for example...
    # smtpctl encrypt mysupersecretpassword
    $6$tEwwZAWy.bLlIDK0$27WDpDFlCGjIP8pl6aTIazkirsG.f9Ux.Djnl4uZYcgWUsl68ID9q.3k5ndr5AMVYSc1tmSPawaX//OxJHk2e1
* At the other hand we do have openldap which defaults to {SSHA} hashing for example
    # slappasswd -s mysupersecretpassword
    {SSHA}ysPSlo0fJBmbVGQ7B9eJ4+eiuCSLT2XD
* There is some configurability at the openldap side of things that we can configure openldap to use {CRYPT} and configure SHA512 .
I don't have a guide here but this is pretty close I believe... http://www.openldap.org/lists/openldap-technical/201408/msg00098.html
* Conclusion even if we configure openldap to store its passwords using SHA512 crypt 3 based hashes similar to how OpenSMTPd generates passwords we will still need some changes as the resulting strings are not easily comparable. We would need to strip {CRYPT} prefix from the openldap password and we would have to remove ///randomsalt from the opensmtpd password.
I think we need a change for opensmtpd table-ldap to support real user credentials binds in order to make some real good use of ldap.

Or is there a different approach to this?

**Comment by cdidier** [comment]
I tried to solve this by adding a new table service (K_CHECKUSER) which will send the user and the password to the table backend. Then the LDAP table backend just need to try to connect to the server using those credentials to authenticate the user.

See https://github.com/OpenSMTPD/OpenSMTPD/pull/903 and https://github.com/OpenSMTPD/OpenSMTPD-extras/pull/55.

**Comment by poolpOrg** [comment]
I'm not convinced that this is an issue nor that it should be solved through a new K_CHECKUSER lookup service and will explain my rationale below so it can be discussed.

First of all, K_CREDENTIALS was introduced to lookup credentials for a user so I'm not convinced that adding a new K_CHECKUSER lookup service because of a supposed shortcoming in K_CREDENTIALS is the way to tackle the issue, i'd rather find a way to "fix" K_CREDENTIALS if there's an issue.

Then, tables are a mechanism to lookup values not to authenticate, they will grab a value from somewhere and pass it to an authentication layer which is not within tables. So I think the whole rationale that:

>- So by knowing OpenSMTPd does not bind to ldap with user provided credentials I think we have to configure the same password hashing scheme for opensmtpd and openldap. This is kinda unfortunate as this is something ldap is supposed to address and we should not have to wory about password schemes, hashing and similar stuff.

and:

>- So at one hand we do have OpenSMTPd with its built-in non-configurable crypt 3 password hashing (on my system these are SHA512 hashes, the crypt implementation and configuration may differ I think) for example...

seems off-scope to me because OpenSMTPD authenticate using crypt(3) by default, which indeed will require credentials to be adapted for that function, but it does so through bsd_auth(3) on OpenBSD and may be configured to use pam(3) on other systems, so you may just delegate authentication to an ldap layer if you actually don't want the system's auth to take place.

This seems like the right approach to tackle this issue to me, if I were to authenticate against ldap, I'd use an ldap authenticator for bsd_auth(3) or pam(3).

**Comment by poolpOrg** [comment]
No discussion took place around this feature request opened almost 2 years ago, I still think it's not the table purpose to perform authentication and given that it can be achieved with bsd_auth(3) or pam(3), I consider this won't go anywere now
