### ISSUE TITLE
Differentiate between failed password and inexistent user login attempts in OpenSMTPD logs.

### ISSUE THREAD

**Issue by whataboutpereira** [OpenSMTPD/OpenSMTPD#843]
Hello!

I've written a Logwatch script for myself for OpenSMTPD, but there is one thing I really miss in OpenSMTPD logs.

Right now we simply get a message notifying about authentication failures, but it actually doesn't tell us if it's a failed password attempt or a missing user.

smtp event=authentication user=test address=192.168.1.100 host=any.host.com result=permfail

I'm hoping further refinement to the log string could be made in the future to differentiate between different types of login failures.

Thanks!
Reio

**Comment by poolpOrg** [comment]
I'm not too convinced yet if this is a good idea but given that it would require code in the privileged process as well as the lookup process as well as the smtp engine and given how close we are to the 6.4.0 release, I'll postpone the decision to 6.5.0 so it can be discussed with @ericfaurot further more.

**Comment by poolpOrg** [comment]
This was discussed a while ago with @ericfaurot and we both think it is a bad idea.

OpenSMTPD already tells you what user was tested and the authentication result, it doesn't care if the auth failure was caused by an inexistant username or an invalid password, from its point of view its the same.

What you want can be achieved through external scripting so we're not going to implement it, sorry.
