### ISSUE TITLE
opensmtpd fails to route IPv4/IPv6 addresses when using relay source

### ISSUE THREAD

**Issue by sumdog** [OpenSMTPD/OpenSMTPD#866]
I've got opensmtpd running on a box that has multiple IP addresses and I want to ensure outgoing mail only gets sent from certain IP addresses (one IPv4 and one IPv6 which have correct reverse DNS set on them).

Say I have the following table (I've scrubbed my real addresses):

    table sendip { 45.76.172.100, 2001:1000:1000:1000:1000:1000:1000:1 }

and I have the following to relay outbound mail after it's been signed by DKIM proxy:

    accept tagged DKIM for any relay source <sendip> hostname mail.example.com

I'll then see the following in the logs:

```
Jul 17 16:58:24 image smtpd[78530]: ad3f7fdb13eb35c1 mta event=connecting address=smtp+tls://216.32.181.10:25 host=mail-co1nam030010.inbound.protection.outlook.com
Jul 17 16:58:26 image smtpd[78530]: ad3f7fdc3b0cb7c0 mta event=connecting address=smtp+tls://216.32.180.42:25 host=mail-by2nam030042.inbound.protection.outlook.com
Jul 17 16:58:28 image smtpd[78530]: smtp-out: Address family mismatch on [connector:IPv6:2001:1000:1000:1000:1000:1000:1000:1->[relay:students.tntech.edu,sourcetable=sendip,heloname=mail.example.com
```

I've tried to specify IPv6 on the outbound list explicitly too:

        table sendip { 45.76.172.100, ipv6:2001:1000:1000:1000:1000:1000:1000:1 }

and get the same error when sending to IPv4 SMTP servers. Why is opensmtpd not selecting the correct IP address for the correct protocol? 

Versions:
OpenBSD 6.3
OpenSMTPD 6.0.4

**Comment by poolpOrg** [comment]
We will be looking into fixing this for the upcoming 6.4.0 release, it will definitely be fixed for 6.5.0 if we miss the window.

**Comment by ericfaurot** [comment]
As I read it, this is just a warning in the logs, but the mails should still be relayed using the other source address in the list.

Can you confirm this?

**Comment by sumdog** [comment]
This might actually be invalid. I was on a VM with SMTP blocked outgoing, so it might have been failing outgoing IPv4, exhausted the IPv4 IPs it looked up and attempted IPv6. Will attempt to replicate in a VM.

**Comment by poolpOrg** [comment]
Discussed in length with @ericfaurot, summary below:

Neither one of us thinks this is an issue: the log you see is warning you that a route can't be established between an inet6 source address and and inet4 mx. This doesn't prevent the mail from flowing as it will take another route.

The message might be confusing, but removing it would be even more confusing because then if you didn't have another route available, there would be no indication in the logs that something went wrong.

We have a ticket to rework the MTA and this source address selection will be completely revamped then, so its not worth pouring efforts in this ticket given the efforts vs benefits.
