### ISSUE TITLE
With 6.4.0 there no longer is a way to match against multiple negative-tags

### ISSUE THREAD

**Issue by Ekleog** [OpenSMTPD/OpenSMTPD#922]
Before, `accept tagged ! A tagged ! B` worked to accept messages that were neither of two tags.

Now, `match ! tag A ! tag B` fails, saying the “tag” match has already been used.

**Comment by poolpOrg** [comment]
Nope, you are confused which is no wonders given that the previous format was confusing:

Before, `accept tagged ! A tagged ! B` worked _only_ to accept messages that were not tagged ! B and it didn't warn you that it was discarding ! A by overwriting the tag name. It has therefore never worked like you thought it did and there was _no way_ to have multiple tags matched one a rule as the rule stored a single tag name.

Now, `match ! tag A ! tag B` fails, like it should always have, because you are using the same keyword twice, but the difference is that it is now capable of taking a table as parameter so you can `match ! tag "foobar"` just like you can: `match ! tag { "foobar", "barbaz"}`, allowing multiple tags where only one could be used before.
