### ISSUE TITLE
[Discussion] Dockerfile improvements

### ISSUE THREAD

**Issue by ngortheone** [OpenSMTPD/OpenSMTPD#947]
This is a split of PR https://github.com/OpenSMTPD/OpenSMTPD/pull/945

@poolpOrg 
In current state a few problems exist with current Dockerfile setup:

1. Not usable without mounting external volumes `/etc/mail` and `/var/spool/smtpd` for several reasons
1.1. Default configuration file references non-existing `aliases` file
1.2. If nothing mounted to `/var/spool/smtpd` then permissions of the folder are set to 755 by docker (this is how it works unfortunately), or if mounted - permissions of mounted directory are used. This creates a problem because smtpd wants root owned 711 dir, and user mounts a directory has his/hers uid:guid and permissions (which are very unlikely to be)

2. Local delivery is not working:
2.1. Because `/var/mail` does not exist.
2.2. Default config does not allow delivery for local recipients from non-local connection

Suggested solutions from https://github.com/OpenSMTPD/OpenSMTPD/pull/945
1. Add default `aliases` file to container
2. Add container startup script that ensures desired permissions on folders
3. Add `/var/mail` folder
4. Modify default config to allow submitting mail for local recipients from non-local connections

**Comment by fgma** [comment]
My suggestion would be to integrate opensmtpd-extras into the docker container. One could use docker-compose to deploy a complete mail server with dovecot and a database for user management that way.

**Comment by ngortheone** [comment]
That is possible. In fact I was privately working on something similar (more Kubernetes oriented, but swarm can be added to). Having an official docker container is a good way to enable adoption of the application and encourage people to give it a try. I often search Dockerhub when I want to try a new thing.

But we should distinguish different goals that docker may serve:

- One is ease of development. With properly setup container you don't need install any dependencies, or configure you system. Just write some code and then `docker build` - and you get a clean build every time.

- Two is delivery mechanism for end users. Some users dont want installing extra dependencies, or maybe they already have a similar service running on the same port - they can easily run OpenSMTPD in a container (this is where swarm or kubernetes also come along) and give it a spin.

But then one could argue that dockerfile and its surroundings should be moved to a separate repository, since it contains code not only from this repo. And a lot of projects do that - they have a separate repository for docker.

I am happy to do this, it all comes down to what Gilles decides is best.

**Comment by poolpOrg** [comment]
Bear with me as I'm not too familiar with Docker, I'll state my state of mind regarding Docker first then answer the individual points, possibly raising other questions.

First of all, the OpenSMTPD project will not provide or endorse a "usable" setup or image that people can deploy to have a working instance out of the box and already properly configured to run. This is not a bad idea or anything, but this is a goal for a more specific project using OpenSMTPD as a brick. The main reason behind that is that there are both code bugs and exploitation bugs, and we only want to care about code bugs, not how a Docker image is behaving at one point in time independently of OpenSMTPD, on a specific host. When we have an "official" image, then we have to support it which is something we really don't want to do because... not our goal. That we have an image people can run to test their code locally is a thing, that these people deploy them to receive mail in production is another.

Then, there's obviously a lot of value in supporting Docker, but as far as I am concerned this is a development environment. I'd be very happy making everything as smooth as possible for docker so it allows us to automate build on various distribution images and drastically increase our CI, it would be really awesome. I have absolutely no objection helping make this but it has to be as isolated as possible, as close as possible to a single file, because when other folks using other stacks want to make it possible to do CI using their own container technologies, we don't want our repository to be a mess of plumbing files for all these techs. Ideally, if we could have an OpenSMTPD-Docker repository which contained all of the docker plumbing and which pulled the OpenSMTPD repository, I would be very happy because essentially anything could be done there without making the OpenSMTPD repository a mess.


Now for the specific answers:

@ngortheone 
> 1. Not usable without mounting external volumes `/etc/mail` and `/var/spool/smtpd` for several reasons
>    1.1. Default configuration file references non-existing `aliases` file
>
>    1.2. If nothing mounted to `/var/spool/smtpd` then permissions of the folder are set to 755 by docker (this is how it works unfortunately), or if mounted - permissions of mounted directory are used. This creates a problem because smtpd wants root owned 711 dir, and user mounts a directory has his/hers uid:guid and permissions (which are very unlikely to be)
>
> 2. Local delivery is not working:
>    2.1. Because `/var/mail` does not exist.
>    2.2. Default config does not allow delivery for local recipients from non-local connection
> 
> Suggested solutions from #945
> 
> 1. Add default `aliases` file to container
>

okie dokie, will commit a trimmed down version of:

https://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/src/etc/mail/aliases?rev=1.67

> 2. Add container startup script that ensures desired permissions on folders
>

yeah why not, but can this be handled in a repository that's not the main repository ?

> 3. Add `/var/mail` folder

ok by me

> 4. Modify default config to allow submitting mail for local recipients from non-local connections

modifying the default config to do that is not an option because by default we want users to not be exposed to the world before they actually explicitly make the tweak, this is the default for OpenBSD daemons and the default we stick to. Is this because it prevents the host from sending mail to the container ?

@fgma 
> My suggestion would be to integrate opensmtpd-extras into the docker container. One could use docker-compose to deploy a complete mail server with dovecot and a database for user management that way.
>

OpenSMTPD-extras will ultimately bite the dust as the underlying API is being rewritten to adopt a similar pattern as for filters, allowing people to write tables/queues using stdin/stdout filters. I don't know what you have in mind with regard to extras but they are in maintenance until I have rewritten the addons, no further development but bugfixes can happen in them.



@ngortheone 
> That is possible. In fact I was privately working on something similar (more Kubernetes oriented, but swarm can be added to). Having an official docker container is a good way to enable adoption of the application and encourage people to give it a try. I often search Dockerhub when I want to try a new thing.
> 
> But we should distinguish different goals that docker may serve:
> 
> * One is ease of development. With properly setup container you don't need install any dependencies, or configure you system. Just write some code and then `docker build` - and you get a clean build every time.
> * Two is delivery mechanism for end users. Some users dont want installing extra dependencies, or maybe they already have a similar service running on the same port - they can easily run OpenSMTPD in a container (this is where swarm or kubernetes also come along) and give it a spin.
> 
> But then one could argue that dockerfile and its surroundings should be moved to a separate repository, since it contains code not only from this repo. And a lot of projects do that - they have a separate repository for docker.
> 
> I am happy to do this, it all comes down to what Gilles decides is best.

Ease of development, clearly and only ease of development. I want you and me and others to be able to provide containers as separate projects, but the OpenSMTPD projects doesn't want to be in the business of delivering ready-to-use containers to users.

**Comment by fgma** [comment]
> OpenSMTPD-extras will ultimately bite the dust as the underlying API is being rewritten to adopt a similar pattern as for filters, allowing people to write tables/queues using stdin/stdout filters. I don't know what you have in mind with regard to extras but they are in maintenance until I have rewritten the addons, no further development but bugfixes can happen in them.

@poolpOrg I'm in the process of  evaluating a mailserver setup based on opensmtpd. I need virtual users from some sort of database. Reading @ngortheone's posting I thought it might be nice to have a full featured docker container as a base also for other users. In the end I don't really care if it is opensmtpd-extras or something new providing the same functionality. 

As you've already written you don't like to support a full-blown docker which I perfectly understand. I hope with the openssl vs. libressl issues resolved 6.6 will have a wider availability in linux distributions as I can't run openbsd on my production servers for now.

**Comment by poolpOrg** [comment]
No doubt, there's no reason it can't be made available in most distributions.

The only known problem so far is the musl based distros

**Comment by ngortheone** [comment]
> The only known problem so far is the musl based distros

My preliminary tests show that openssl works OK on musl based distro - alpine linux. I haven't done any serious testing by any means though.

> > Add default aliases file to container

> okie dokie, will commit a trimmed down version of:
> https://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/src/etc/mail/aliases?rev=1.67

@poolpOrg  opened an issue to track this https://github.com/OpenSMTPD/OpenSMTPD/issues/949

> add /var/mail folder

I will create a PR with this soon

> > Add container startup script that ensures desired permissions on folders

> yeah why not, but can this be handled in a repository that's not the main repository ?

Yes. Given your answer I propose 2 different solutions. 

1. Dockerfile(or maybe 2, one for musl and one for normal libc) in this repository that is focused on building/testing OpenSMTPD

2.  Separate community repo  where all the things that are out of the scope of  main OpenSMTPD, where we can put things that @fgma described. (Why not create a `docker` fiolder in extras repo?)


>  I'd be very happy making everything as smooth as possible for docker so it allows us to automate build on various distribution images and drastically increase our CI, it would be really awesome. I have absolutely no objection helping make this but it has to be as isolated as possible, as close as possible to a single file, 

We can have one dockerfile per distribution:version pair. It would provide a reference for package maintainers on how to build OpenSMTPD.


> modifying the default config to do that is not an option because by default we want users to not be exposed to the world before they actually explicitly make the tweak, this is the default for OpenBSD daemons and the default we stick to. Is this because it prevents the host from sending mail to the container ?

Yes. I will try to give you a little explanation how to think about this problem. Basically docker works like a VM (this is a gross oversimplification, but fair to explain the basics), but instead of the hypervisor, that emulates hardware Linux kernel uses cgroups and namespaces to isolate the processes inside the container. Basically container shares the same kernel with your host system, but everything else is isolated - process IDs, filesystem, network interfaces etc.

So docker has its own network interface and IP address that is isolated from the rest of the system. When user runs the container `docker run -p 2222:22 opensmtpd-dev` he/she specifies what container ports should be available to the host system. In this example on my host system traffic sent to  `localhost:2222` will  be seen inside docker's as traffic incoming on  22 from network. So the application inside docker will get traffic marked with the IP of your host system, not 127.0.0.1. And default OpenSMTPD configuration only accepts mail from local loopback. 

So a problem I see here is that it is hard to test certain things in a "default config", "local-only" scenario. Thinks like TLS for example require modifications to config file, require generation of the certs and external client submitting mail. And you probably want to test those cases during the dev cycle.
So IMHO a bit of a scripting glue to dev docker file is required, just to prepare the container for a full-scale testing.

**Comment by whataboutpereira** [comment]
I wonder if some of these changes will let me run OpenSMTPD in a LXC as well. Tried it, got some errors and turned to Postfix for now. Oh! The blasphemy!

**Comment by poolpOrg** [comment]
@ngortheone ok for how you intend to do things

I'll give the IP issue some thinking this week-end, I understand how the default config is not usable in this context, maybe we can provide a "container" default config ?

The #949 issue also highlights that we may need an etc/ directory at the root of portable branch, because in the master branch we don't ship any files since they are part of the base system, and in portable branch we ship an smtpd.conf file that is part of the src/ which is not good either.

Maybe we should have an etc/ directory in portable with a default aliases file + a default config file + a default config file for containers ?

**Comment by ngortheone** [comment]
@poolpOrg I think that `etc` dir is a good idea to have various configs for different usecases

**Comment by ngortheone** [comment]
We should also move dockerfile to its own folder, especially if we want a dockerfile per each distro.

Something like:
```
docker/
    Dockerfile.alpine
    Dockerfile.ubuntu
    ...
    Dockerfile.yourdistronamehere
```

**Comment by poolpOrg** [comment]
is it ok to close this issue ?
