### ISSUE TITLE
[Question] alternative build systems

### ISSUE THREAD

**Issue by ngortheone** [OpenSMTPD/OpenSMTPD#954]
It is not a secret that autotools are not user friendly, complicated and slow.

Modern build tools like CMake+Ninja or Meson are much frendlier, have better editor/IDE support and provide faster build times. 

[LibreSSL](https://github.com/libressl-portable/portable) supports CMake.

Also [OpenBSD policy](https://www.openbsd.org/policy.html) states: 
>  For historical reasons, the OpenBSD base system still includes the following GPL-licensed components: the GNU compiler collection (GCC) with supporting binutils and libraries, GNU CVS, GNU texinfo, the mkhybrid file system creation tool, and the readline library. Replacement by equivalent, more freely licensed tools is a long-term desideratum.

CMake will also allow easier switch to clang later.

So the question here: what is the OpenSMTPD's official stance on this issue? I understand that this might not be a top priority, but will PRs adding  Cmake support are going to be welcome?

**Comment by poolpOrg** [comment]
OH DAMN I hit back and forward and lost my comment :-(

ok, let me type it again:

I hate autotools, I'm a vocal hater of that pile of poo, I have literally had a branch called `autohell` so you can trust me when I say: I'm not a proponent of that framework.

That being said:

- I'm the only one working there at the moment so any new framework is going to annoy me
- If we have two build systems, I still get to maintain both wether I'm alone or not working there
- autoconf, as shit as it is, produces a vendor dependency, not a user dependency
- the resulting configure script is very portable to shells as different as pdksh and bash
- we can share bits of configure.ac and m4 macros with OpenSSH, OpenNTPD, OpenBGPD, ...

I'm not a big fan of having multiple build systems and unless we have a very good reason to switch to something else, I'd rather keep autoconf because it's not user friendly, it's complicated and slow, but it's also very familiar and we know what the downsides are, what should be improved, where to look at.

The OpenBSD policy doesn't apply here because OpenBSD doesn't use the portable branch and doesn't rely on the build system, it uses the mk framework, you don't need autotools/libtool and such on OpenBSD to build OpenSMTPD.

With regard to clang, I'm unsure I understand because I built with clang on multiple systems, can you elaborate ?

There's no official stance but mine at this point because I'm the only developer who actually does portability stuff in OpenSMTPD :-)

**Comment by poolpOrg** [comment]
is it ok to close this issue ?
